### PR TITLE
[gui-tests][full-ci] check the keyring and try to unlock if locked

### PR DESCRIPTION
**Pull request by saw-jan**
Check the keyring locked status and try to unlock it if locked during the test execution.

Fixes https://github.com/owncloud/client/issues/11883

Depends on: https://github.com/owncloud-ci/squish/pull/63

:x: Test fails because keyring can be locked during the test execution: https://drone.owncloud.com/owncloud/client/19470/1/10
```
--------------Scenario 1 (PASS)
LOG:   Start Scenario	login after logging out normal Account
LOG:   CompletedProcess(args=['busctl', '--user', 'get-property', 'org.freedesktop.secrets', '/org/freedesktop/secrets/collection/login', 'org.freedesktop.Secret.Collection', 'Locked'], returncode=0, stdout=b'b false\\n', stderr=b'')	
LOG:   b false\n
...
LOG:   End Scenario	login after logging out normal Account

--------------Scenario 2 (FAIL)
LOG:   Start Scenario	login after logging out normal Account
LOG:   CompletedProcess(args=['busctl', '--user', 'get-property', 'org.freedesktop.secrets', '/org/freedesktop/secrets/collection/login', 'org.freedesktop.Secret.Collection', 'Locked'], returncode=1, stdout=b'', stderr=b'Failed to get property Locked on interface org.freedesktop.Secret.Collection: Message recipient disconnected from message bus without replying\\n')	
LOG:   Failed to get property Locked on interface org.freedesktop.Secret.Collection: Message recipient disconnected from message bus without replying\n
...
LOG:   Start Step	Then user "Alice" should be connected to the server
ERROR: Script Error	TimeoutError: Timeout waiting for the account to be connected for 5000 milliseconds
```

:heavy_check_mark: Checking and trying to unlock keyring works: https://drone.owncloud.com/owncloud/client/19477/2/10
```
--------------Scenario 1 (PASS)
LOG:   Start Scenario	login after logging out
LOG:   b false\n
...
LOG:   End Scenario	login after logging out

--------------Scenario 2 (PASS)
LOG:   Start Scenario	login after logging out
LOG:   Failed to get property Locked on interface org.freedesktop.Secret.Collection: Message recipient disconnected from message bus without replying	
LOG:   Unlocking keyring...
...
LOG:   End Scenario	login after logging out
```

### CODE REVIEW

**Comment by saw-jan** [comment]
Unlocking keyring works: https://drone.owncloud.com/owncloud/client/19491/1/10

**Comment by saw-jan** [comment]
Hopefully this won't come in the future :crossed_fingers:

**Review by PrajwolAmatya — APPROVED** [review]

**Comment by saw-jan** [comment]
I will wait for GUI tests to get fixed (#11898) before merging it.

**Comment by saw-jan** [comment]
I want to merge this now because the tests are failing because of keyring thing. CI will not pass because of 11898.

**Pull request merged**
