### PR TITLE
Fix registry key syntax in FAQ.

### PR DESCRIPTION
**Pull request by RealRancor**

### CODE REVIEW

**Comment by RealRancor** [comment]
Not quite sure which other branches this needs to be commited that it gets fixed at https://doc.owncloud.org/

**Comment by danimo** [comment]
2.0 currently

**Comment by danimo** [comment]
Done, see 2c9d41842367e0379a21c714ae165ae1140cdf8f

**Comment by RealRancor** [comment]
Thanks! :+1:

**Pull request merged**
