### PR TITLE
[tests-only] Notify with logs whenever there is a nightly fail

### PR DESCRIPTION
**Pull request by saw-jan**
Uses the custom template for build notification

Example:
notifications

Fixes https://github.com/owncloud/client/issues/9479

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11175/2/1
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11175/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/11175/guiReportUpload/serverlog.log)

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11176/2/1
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11176/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/11176/guiReportUpload/serverlog.log)

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11180/2/1
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11180/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/11180/guiReportUpload/serverlog.log)

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11192/2/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11192/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/11192/guiReportUpload/serverlog.log)
Screenshots:
- [simple_sharing_with_user.png](https://cache.owncloud.com/public/owncloud/client/11192/guiReportUpload/screenshots/simple_sharing_with_user.png)

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11193/2/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11193/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/11193/guiReportUpload/serverlog.log)
Screenshots:
- [simple_sharing_with_user.png](https://cache.owncloud.com/public/owncloud/client/11193/guiReportUpload/screenshots/simple_sharing_with_user.png)

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11195/2/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11195/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/11195/guiReportUpload/serverlog.log)
Screenshots:
- [simple_sharing_with_user.png](https://cache.owncloud.com/public/owncloud/client/11195/guiReportUpload/screenshots/simple_sharing_with_user.png)

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11197/2/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11197/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/11197/guiReportUpload/serverlog.log)
Screenshots:
- [simple_sharing_with_user.png](https://cache.owncloud.com/public/owncloud/client/11197/guiReportUpload/screenshots/simple_sharing_with_user.png)

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11199/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11199/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/11199/guiReportUpload/serverlog.log)
Screenshots:
- [remove_an_account_connection.png](https://cache.owncloud.com/public/owncloud/client/11199/guiReportUpload/screenshots/remove_an_account_connection.png)
- [remove_the_only_account_connection.png](https://cache.owncloud.com/public/owncloud/client/11199/guiReportUpload/screenshots/remove_the_only_account_connection.png)

**Review by Talank — APPROVED** [review]

**Pull request merged**
