### PR TITLE
Wizard errors in a scroll area 

### PR DESCRIPTION
**Pull request by ckamm**
Another attempt at #6546

How about this?

### CODE REVIEW

**Comment by guruz** [comment]
(Code looks ok, havent tested it)

**Comment by ogoffart** [comment]
I ran the code and it does not look so pretty when there is an error.
Maybe not related, but the spinner continues to spin, and that's what is causing the scrollbar to appear.

I'm wondering if it makes sense at all to have error there.
Network error should be shown in the UI anyway if they occurs. No need to check for network connectivity here.

Error while creating the local folder should stay there, but maybe they can be put right bellow the button.

**Comment by ckamm** [comment]
I removed the leftover debug for starting a spinner when one of the radio buttons was clicked. I didn't touch the spinner show/hide much, so I'm surprised you see that. 

Agree that this is pretty painful and removing the error from this screen would simplify things.

**Comment by guruz** [comment]
Show the error in a non-modal QMessageBox?
Something similar in https://github.com/owncloud/client/blob/46077f0de238298a8688f3ba8c4ab0c7fb3daf54/src/gui/owncloudsetupwizard.cpp#L286 ?

**Comment by guruz** [comment]
tested by @jnweiger https://github.com/owncloud/client/issues/6546 .. merging

**Comment by guruz** [comment]
CI failure is unrelated, CC @tboerger 
```java.io.IOException: Failed to rm container '3726526c32c7985378b69a8e57caf55743ef48001955f70382b8f3c96ecdc65d'.```

**Comment by tboerger** [comment]
I think we can drop the jenkins pipeline, than we won't get these errors anymore.

**Comment by guruz** [comment]
If it runs the same tests: sure. Maybe @DeepDiver1975 needs to remove it from the repo here?

https://drone.owncloud.com/owncloud/client/392/5
https://jenkins.owncloud.org/job/owncloud-client/job/client/job/PR-6589/5/consoleFull
Only difference seems to be logging level.

**Comment by tboerger** [comment]
Yeah, Drone is not running in with full logging because it will cut off the output because it got some limitiation related to that. But beside this difference Drone seems to be doing a good job and we are another step forward to get rid of Jenkins.

**Pull request merged**
