### PR TITLE
updates to user manual for 2.1.1

### PR DESCRIPTION
**Pull request by carlaschroder**

### CODE REVIEW

**Comment by carlaschroder** [comment]
Please review @danimo @dragotin @ogoffart

**Comment by carlaschroder** [comment]
I give me a :+1: !

**Comment by danimo** [comment]
You asked for a review, so here you go:

- Wrong branch (2.1.1 is a temp. release branch that will go away, should go to 1.1)
- Images inconsistent (yes, I know you hate windows :)
- See other comments.

**Comment by carlaschroder** [comment]
Ah, that was a mistake to merge with 2.1.1.
You're stuck with the screenshots until I sort out some windows problems. Closing to do-over.

**Pull request closed without merging**
