### PR TITLE
Don't crash if a delete job marked as ignore is cancelled

### PR DESCRIPTION
**Pull request by TheOneRing**
Issue: #7967

The enforce was introduced in https://github.com/owncloud/client/commit/4d9748080958aaee55810f52a3e14dda024dffa1

### CODE REVIEW

**Review by dschmidt — COMMENTED** [review]
Better let someone else comment on this, no idea about this.

**Comment by ogoffart** [comment]
It should probably be possible to write a test for that and I highly recommend doing that to avoid regressions.
I guess the patch is correct although I don't explain how the ignore item gets in the delete items list.

**Comment by TheOneRing** [comment]
Yes we should probably write a test for that, but I was not able to trick the test system into those conditions.
The actual scenario is 
Clipboard - August 18, 2020 3_20 PM

Now we move a file in this folder. The move fails with a 403, we have a delete on the original file (legacy code?) which gets marked as ignore.

Here a log 
[log.txt](https://github.com/owncloud/client/files/5107630/log.txt)

**Comment by TheOneRing** [comment]
See https://github.com/owncloud/client/issues/8066

**Pull request closed without merging**
