### PR TITLE
ownsql: handle QByteArray without converting to QString

### PR DESCRIPTION
**Pull request by ogoffart**
QByteArray is used for checksum

### CODE REVIEW

**Comment by ogoffart** [comment]
( extracted from https://github.com/owncloud/client/pull/5056 )

**Comment by dragotin** [comment]
:+1: 

Maybe we should remove the default case and error log so that we notice next time in case we introduce a new data type.

**Comment by guruz** [comment]
Why not use sqlite3_bind_blob ?

**Comment by ogoffart** [comment]
> Why not use sqlite3_bind_blob ?

I don't know? Why use it?  Currently all the QByteArray only contains text.

**Comment by guruz** [comment]
OK 👍  if you take the risk that if we ever change that something bad happens.
Although the function has a size parameter so maybe it's OK.
(And we anyway always get text from WebDAV)

**Comment by ogoffart** [comment]
Any other than a string was not working before because we were converting to QString anyway.

**Pull request merged**
