### PR TITLE
Update "..." menu documentation to master

### PR DESCRIPTION
**Pull request by phil-davis**
This menu in 2.0.* now has 4 options.
The small screenshot needs updating also. @carlaschroder it is probably best if you take a new screen shot from whatever client version you have been using for screen shots. That way they will all have a consistent look.

### CODE REVIEW

**Comment by danimo** [comment]
This belongs into 2.0 branch, not master, if it's supposed to go into 2.0.2. Any chance you can rebase it and send a new pull request? Otherwise I'd cherry-pick your change.

**Comment by phil-davis** [comment]
Either way that you like - it either needs to go in the 2.0 series branches and be merged forward for the future, or into master and be cherry-picked backward.
If you want me to make it against a 2.0-series branch then let me know exactly which one 2.0.2 or just 2.0 or?

**Comment by phil-davis** [comment]
I made PR https://github.com/owncloud/client/pull/3931 to 2.0 branch.
So review and choose whichever way you want to do the committing.

**Comment by danimo** [comment]
tnx!

**Pull request closed without merging**
