### PR TITLE
Wizard: Make the wizard a child dialog of the settings

### PR DESCRIPTION
**Pull request by TheOneRing**

### CODE REVIEW

**Comment by TheOneRing** [comment]
image

**Comment by TheOneRing** [comment]
image

**Comment by TheOneRing** [comment]
I changed the default size of the dialog, one issue is that the client saves the size so most users will keep the small one.
We could set a minimum size, the current value of 800x500 should fit on all screens.
Also I guess the Wizard should get a cancel button as currently the is no indication on how to abort (Esc).

**Comment by michaelstingl** [comment]
Yeah, cancel makes sense.

**Comment by TheOneRing** [comment]
image

**Comment by TheOneRing** [comment]
Or the cancel button on the left?
image

**Comment by michaelstingl** [comment]
Yeah, cancel better left 👍

**Comment by dschmidt** [comment]
I agree, the outer right button should ne next, so cancel left.

**Comment by TheOneRing** [comment]
Done ready for review

**Pull request merged**
