### PR TITLE
Provide "restart required" dialog on Windows, too

### LINKED ISSUE #10980: Extend "restart required" dialog to Windows
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

I am getting an ownCloud notification when I log in to my PC that there is an update available and that I should restart the client to start the update.  However, restarting the client nor restarting the PC results in the update starting.

### Expected behavior

I expect that after closing the program, I should get a UAC request in windows to allow the updater to run.

### Steps to reproduce the issue

Start the owncloud client.
Get the pop up.
right click on the owncloud client taskbar tray icon and select quit owncloud.
Wait.

### Screenshots

https://cloud.owncloud.com/s/mFEXiz1bCBku780

### Logs

https://cloud.owncloud.com/s/k4hSM1oadCTx8K0

### Client version number

[4.0.10896](https://download.owncloud.com/desktop/ownCloud/stable/4.0.0.10896/win/)

### Desktop environment (Linux only)

_No response_

### Client package version and origin (Linux only)

_No response_

### Installation path (Windows only)

c:\program files\owncloud\owncloud.exe

### Server information

cloud.owncloud.com

### Additional context

For reference, while collecting the system information and unrelated program, Notepad++, showed an upgrade was available and its behavior was as expected.

### PR DESCRIPTION
**Pull request by fmoc**
This commit provides a remodeled version of the "Update finished" dialog implemented in #11201.

Fixes #10980.

screenshot_2023-12-15_16-07-41

screenshot_2023-12-15_18-05-15

### CODE REVIEW

**Review by TheOneRing — CHANGES_REQUESTED** [review]
As far as I can remember, the current message also allowed a user to decline an update.
So we need `Skip update`, `Restart and update`, `Update later`

**Comment by TheOneRing** [comment]
Also please add a changelog entry

**Comment by fmoc** [comment]
> As far as I can remember, the current message also allowed a user to decline an update.
> So we need Skip update, Restart and update, Update later

There is a "no URL dialog" in the NSIS updater class that offers these options but isn't regularly shown apparently. This dialog is shown when the update has been downloaded sucessfully already.

We need to think about consolidating all these (partially redundant) dialogs. However, this is outside of this PR's scope, which replaces a specific systray message with a dialog.

**Comment by TheOneRing** [comment]
image
your right

**Review by TheOneRing — APPROVED** [review]

**Pull request merged**
