### PR TITLE
Structure developer documentation

### PR DESCRIPTION
**Pull request by danimo**
- rename target "doc-dev"
- group into modules
- move to doc/dev

### CODE REVIEW

**Comment by danimo** [comment]
@owncloud/desktop-developers @carlaschroder

**Comment by danimo** [comment]
I've assumed that we want Qt style comments, even tough we used both before. Any preferences?

**Comment by carlaschroder** [comment]
This is over my head, so I have nothing helpful to offer except this represents a lot of work! Good job. Now let's see that good code commenting commence :) Which really does help-- for example, I read the oC source code looking for clues to how things are supposed to behave.

**Comment by danimo** [comment]
@carlaschroder That's exactly the purpose. Thanks! :)

**Comment by ogoffart** [comment]
by Qt style, you mean '/*!'  vs. '/**'  ?  
Personally i prefer the doxygen style '/**' as this is what is used everywhere outside Qt.   But '/*!' is fine too if doxygen supports it.

**Comment by danimo** [comment]
The `/*!` notation is consistent with the stuff in 3rdparty and doxygen doesn't care...

**Comment by danimo** [comment]
csync also uses doxygen style, so what the hell :)

**Pull request merged**
