### PR TITLE
[ci] Make changelog push to the master branch only

### PR DESCRIPTION
**Pull request by saw-jan**
Nightly fail: https://drone.owncloud.com/owncloud/client/15538

Currently, changelog pipeline in 4 branch tries to push the diff to the master branch.
As per https://github.com/owncloud/client/pull/10895#issuecomment-1569749623, we only push changelog on master branch only

### CODE REVIEW

**Comment by TheOneRing** [comment]
The 4 branch must not push anywhere.
Changelog must only be pushed on master.
Else merges get insane.

Changelog generation on 4 is only for linting.

**Review by TheOneRing — CHANGES_REQUESTED** [review]
^

**Comment by saw-jan** [comment]
@TheOneRing One question. Will it worth running chagelog in release branches (4)?
If not then maybe we can run changelog in master only. But if good have changelog running in 4 then we can prevent push step from running.

**Comment by TheOneRing** [comment]
Changelogs for tags are currently manually generated.
We can probably skip the changelog step on branches and only run it in pr's (for linting) and on master.

**Comment by saw-jan** [comment]
> Changelogs for tags are currently manually generated. We can probably skip the changelog step on branches and only run it in pr's (for linting) and on master.

So then I will limit the changelog pipeline to `master` branch only

**Review by TheOneRing — APPROVED** [review]

**Review by fmoc — APPROVED** [review]

**Pull request merged**
