### PR TITLE
Gui: Mark non vfs settings explicitly

### PR DESCRIPTION
**Pull request by TheOneRing**
See #8107 for screenshots

### CODE REVIEW

**Comment by dschmidt** [comment]
I'm torn:
I think the structure is good but box in box in box isn't really optimal ... maybe we can get away with a regular column based layout and headlines at the top?

**Review by dschmidt — COMMENTED** [review]
I'm torn:
I think the structure is good but box in box in box isn't really optimal ... maybe we can get away with a regular column based layout and headlines at the top?

**Comment by TheOneRing** [comment]
Hm there is no real column based design element.
I also think that it is a bit cramped...
I could move the non virtual files only group out to its own seperate section like netowrk.
Something like "Advamced - Non virtual files"

**Comment by TheOneRing** [comment]
image

**Comment by michaelstingl** [comment]
Maybe new section "Approval of folders (Non virtual file mode only)" or "Folder download approvals (Non virtual file mode only)"

**Comment by TheOneRing** [comment]
"Approval of folders sync (Non virtual file mode only)" ?

**Comment by michaelstingl** [comment]
"Approval of folder sync (Non virtual file mode only)" / "Approval of folder download (Non virtual file mode only)" ?

We’re getting closer…

**Comment by TheOneRing** [comment]
image

**Review by dschmidt — APPROVED** [review]
fine with me, if fine with @michaelstingl

**Pull request merged**
