### PR TITLE
Reconcile: When detecting a local move, keep the local mtime

### PR DESCRIPTION
**Pull request by ogoffart**
Issue https://github.com/owncloud/client/issues/6629#issuecomment-402450691

### CODE REVIEW

**Comment by ogoffart** [comment]
(We might need to cherry pick in 2.4.2)

**Comment by guruz** [comment]
@ogoffart Could we have some info about what you explained on IRC in a code comment around https://github.com/owncloud/client/blob/fabc706e43c54f8a9c7ee89807d16e63948fdb8b/src/libsync/syncfileitem.h#L233 ?

**Comment by guruz** [comment]
Appveyor failure is unrelated
```
executing command: C:\Program Files\Git\cmd\git.exe clone git://anongit.kde.org/craft-blueprints-kde C:\CraftMaster\windows-msvc2017_64-cl\etc\blueprints\locations\craft-blueprints-kde
Cloning into 'C:\CraftMaster\windows-msvc2017_64-cl\etc\blueprints\locations\craft-blueprints-kde'...
fatal: unable to connect to anongit.kde.org:
anongit.kde.org[0: 159.203.184.29]: errno=Invalid argument
Action: fetch for craft/craft-blueprints-kde FAILED
*** Craft all failed: craft/craft-blueprints-kde after 21 seconds ***
fatal error: package craft/craft-blueprints-kde all failed
```
@dschmidt

**Comment by guruz** [comment]
cherry pick in https://github.com/owncloud/client/pull/6635

**Pull request merged**
