### PR TITLE
[Core] Include more information about the OS in the user agent

### PR DESCRIPTION
**Pull request by TheOneRing**
What do you think in general about this?

### CODE REVIEW

**Comment by michaelstingl** [comment]
@TheOneRing how would this look like in the request? Could you post some examples? Win/x64? Linux/ARM?

**Comment by TheOneRing** [comment]
```
"Mozilla/5.0 (Macintosh) mirall/2.7.0git (ownCloud, osx-19.2.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
"Mozilla/5.0 (Windows) mirall/2.7.0git (ownCloud, windows-10.0.18363 ClientArchitecture: x86_64 OsArchitecture: x86_64)"

**Comment by michaelstingl** [comment]
@TheOneRing Thanks! Double-check with @hodyroff ?

**Comment by hodyroff** [comment]
There is no downside, or? Just more information, so good.

**Pull request merged**
