### PR TITLE
Improve Low Disk Space Document

### PR DESCRIPTION
**Pull request by mmattel**
This is an improvement of the low disk space document.
The content renders now much better, some text has been improved and added.
When you do a build or render it with a browser antora plugin, it now looks much more professional

Backport to 2.6 and 2.7

### CODE REVIEW

**Review by TheOneRing — APPROVED** [review]
LGTM

**Comment by TheOneRing** [comment]
Thx for your contribution.
We don't backport, changes targeting 2.7 should go to 2.7 and would be merged back to master.
2.6 is closed.

**Comment by mmattel** [comment]
@TheOneRing
> We don't backport, changes targeting 2.7 should go to 2.7

ok, should I change the target branch to 2.7 (and at all other doc PRs I made here in client) ?
(btw just for my info, why writing to a branch and do a forward port to master. What is the difference to writing to master and doing a backport?)

Note, in case the base branch changes, this would be needed at https://github.com/owncloud/client/pull/8406 too...

**Comment by TheOneRing** [comment]
Yes please target 2.7, you might need some git magic, `git checkout 2.7; git cherry-pick id; git push -f branch_name`force push is allowed in pull requests.

Backporting would mean that we merge to master, cherry-pick the fix to 2.7.
As we apply code fixes to 2.7 and merge that back to master, those doc changes would appear twice in the history.

**Pull request closed without merging**
