### PR TITLE
[Sharing] Make sure the file is actually synced to the server

### PR DESCRIPTION
**Pull request by rullzer**
Before we attemt any sharing make sure the file is synced to the server.

We should make sure actually that non of the file browser plugins tries to share a file if it does not have to proper status.

### CODE REVIEW

**Comment by rullzer** [comment]
Now also the SHARE_STATUS command will reply with `SHARE_STATUS:NOTSYNCED:<FILE>` if the file/folder is not properly synced yet.

**Comment by BuenGenio** [comment]
Actually this change is causing our design team a lot of grief. They used to rely on the ability to share links while the upload is still in progress, as they will sometimes be working late and would send these links in order to meet deadlines, or close the project without forgetting to send those emails, late at night as they wouldn't be read until morning, allowing uploading to complete and the designers to go home. 

Can we make this an option, rather than enforce this change, as it's making defending my case for switching our 100-strong operation from Dropbox to ownCloud that much more difficult (the other one being that there is no delta-sync, and it's taking our 6 designers a month to download 1.5TB worth of data (times 6!) - clogging up everyone else's bandwidth...

Thanks

**Comment by rullzer** [comment]
@BuenGenio well then it just worked by chance. The thing is we do not have any quarantee from the server side that a file is uploaded and available before the sync is done. This has mainly to do with the server internals. If you are uploading a big file which is chunked it is even less safe to do so.

We need to think how to properly do this. But getting the old behaviour back is not right since it is in fact a bug that it was allowed.

**Comment by BuenGenio** [comment]
Well, would something as simple as inserting the link<->path for the file being uploaded into oc_shares as soon as the upload starts work?

Both are known at the very beginning, so should be trivial. Or is there anything else missing I'm not taking into account?

**Comment by rullzer** [comment]
On an abstract level yes. But the reality is a bit more complex. Basically we do not intesert paths into the oc_share table, we insert file ids. And as far as I know they are not guaranteed to be stable until the whole file is uploaded.

**Pull request merged**
