### PR TITLE
add autostart to troubleshooting

### PR DESCRIPTION
**Pull request by voroyam**
instruction what to do when disabling the autostart feature does not work.

removed the note about the server log file [it was a note to self from Matthew]

### CODE REVIEW

**Comment by voroyam** [comment]
@michaelstingl need review

**Comment by voroyam** [comment]
> How about
> image

How about reading what I wrote?

**Comment by TheOneRing** [comment]
In that case we should debug why it does not work

**Comment by TheOneRing** [comment]
I don't think we need to document a temporary workaround.
Can you open an issue for this instead and document what and how it is broken?

**Pull request closed without merging**
