### PR TITLE
CMake: Implement WITH_AUTO_UPDATER

### PR DESCRIPTION
**Pull request by TheOneRing**
Fixes: #9082

### CODE REVIEW

**Review by fmoc — APPROVED** [review]

**Comment by dragotin** [comment]
This needs to be documented in the client docs, there is a paragraph about building the client. @mmattel 

Are there, apart from this switch, ohters that should be documented there?

**Comment by TheOneRing** [comment]
They are already kind of documented in code.
https://github.com/owncloud/client/blob/3ae537b8c4dcfc9c935799baf2f6d855f679bddd/CMakeLists.txt#L80-L105

**Comment by dragotin** [comment]
> They are already kind of documented in code.

yes, and with a cmake-guru-level above 8 people will find that ;-)

**Comment by TheOneRing** [comment]
Those settings are available in the cmake gui and in most IDE's

**Comment by TheOneRing** [comment]
I don't really have a problem with it, its just an other part of the documentation that can be outdated quite fast

**Pull request merged**
