### PR TITLE
Persist tus uploads

### PR DESCRIPTION
**Pull request by TheOneRing**

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests-oc10</strong> https://drone.owncloud.com/owncloud/client/14055/6/1

<details>


</details>

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests-ocis</strong> https://drone.owncloud.com/owncloud/client/14055/7/1

<details>


</details>

**Comment by TheOneRing** [comment]
Depends on the review of multiple other pr's

**Review by fmoc — APPROVED** [review]

**Review by fmoc — APPROVED** [review]

**Comment by Salipa-Gurung** [comment]
Tested. see https://github.com/owncloud/client/issues/8126#issuecomment-1471876754

**Pull request merged**
