### PR TITLE
Rebuild win shell integration

### PR DESCRIPTION
**Pull request by jturcotte**
For #4977, improves the windows build a bit at the same time

### CODE REVIEW

**Comment by guruz** [comment]
I'll let @danimo review this.

Let's remember to have @ArthurChiao test a nightly with this.

**Comment by danimo** [comment]
:+1:

**Comment by ArthurChiao** [comment]
@guruz I tested `ownCloud-2.2.3.6203-nightly20160627-setup.exe`, the problem is fixed, client starts in 1 second.

BTW, Overlay icons on my computer still don't work, but that seems to be another issue.

**Comment by guruz** [comment]
@ArthurChiao Thanks. let's move the overlay discussion to https://github.com/owncloud/client/issues/4977

**Pull request merged**
