### PR TITLE
Introduce X-Original-Request-ID

### PR DESCRIPTION
**Pull request by TheOneRing**
Add an additional header to track reuests that had to be restarted

### CODE REVIEW

**Review by fmoc — APPROVED** [review]
Looks good to me.

**Comment by michaelstingl** [comment]
According to [`RFC-6648`](https://tools.ietf.org/html/rfc6648) (from 2012), we should better avoid introducing new custom headers with "`X-`" prefix. Also see https://tonyxu.io/posts/2018/http-deprecate-x-prefix/ for more information.

**Comment by fmoc** [comment]
Does either server support such a parameter at this point? I couldn't find anything in both code bases.

**Comment by fmoc** [comment]
@michaelstingl is right, according to RFC 6648 the parameter should just be called `Original-Request-ID`.

**Comment by michaelstingl** [comment]
Could also be solved with https://github.com/owncloud/client/issues/7595

opentelemetry uses https://w3c.github.io/trace-context/ (`traceparent`, `tracestate` and `traceresponse`)

**Comment by michaelstingl** [comment]
> Does either server support such a parameter at this point? I couldn't find anything in both code bases.

No, only `X-Request-ID` are displayed in the `owncloud.log`.

But any header can be added to the Apache log:
https://doc.owncloud.com/server/admin_manual/configuration/server/logging/request_tracing.html#web-server-configuration-example
(most middleware can do too)

`opentelemetry` (https://github.com/owncloud/client/pull/8556#issuecomment-824634291) is supported in oCIS with _Jaeger_:
- https://owncloud.dev/ocis/deployment/monitoring-tracing/
- https://owncloud.dev/ocis/development/tracing/

**Comment by TheOneRing** [comment]
I'd still like to merge the request as it really helps to debug the code.
Independent of this change we should discuss proper standard tracing and add it to the roadmap in a joined effort with the server team.

**Comment by michaelstingl** [comment]
> I'd still like to merge the request as it really helps to debug the code.

sure 👍

**Pull request merged**
