### PR TITLE
Conflict view

### PR DESCRIPTION
**Pull request by ckamm**
Shows new and old conflicts in the issue tab:

spectacle n29588
spectacle x29588

### CODE REVIEW

**Comment by ogoffart** [comment]
Looks good to me.

Just wondering if the user will understand how to resolve the conflict

**Comment by ckamm** [comment]
@ogoffart Indeed. Maybe we want to give a link to a page that explains conflicts and ways of resolving them nearby? I thought about whether there should be any buttons on this item, but having "quick resolution" buttons would most likely be dangerous.

Also: I think I'll update the message to include a "Click for details." sentence, to make it clearer that one can click the box to go to the issues tab.

**Comment by SamuAlfageme** [comment]
Once again, really amazing feature to ship in 2.4 ☺️

I have a couple of doubts: 

1. What will happen with non-writable folder conflicts*? Could this be extended to support those too? - see related https://github.com/owncloud/client/issues/5273 
2. Maybe we could adapt something similar as the webUI for conflict resolution?

<p align="center">
  
</p>

(*) -> not really _"conflicts"_ 😁

**Comment by ckamm** [comment]
@SamuAlfageme Can you be more specific about 1. #5273? I don't see how it relates. All existing conflict files will now lead to this message and will be listed in the issues tab.

About 2.: Indeed, we could now provide a better conflict resolution user interface. It needs discussion and design though. The webui like dialog wouldn't be particularly useful in most cases though: Usually users will need to look at both files and create a merge manually.

I think there should be actions for
* "Open folder" (similar to clicking the conflict list entry now)
* "Open synchronized server version"
* "Open unsynchronized local conflict copy"
* "The conflict is resolved, delete the conflict file"
* "The conflict is resolved, overwrite the file with the conflict file"
* "The conflict is resolved, keep both files renaming the conflict file"

That would allow opening, merging and resolving in a convenient way. I'll make a new ticket for that.

**Comment by SamuAlfageme** [comment]
@ckamm - about 1 - I was just wondering if it might be useful to offer the user the chance to see all the "_conflict_" files (e.g. each save he did on the file) that were created (in this same tab) and maybe the count/list of local "_conflicts_" (versions). As I write it, I realize that could be a bit overkill though. 

I can imagine a scenario when the user does not care about having a local file unsynced on a read-only folder and making edits leads him to many of these files. 

Cool ideas in #5896!

**Comment by ckamm** [comment]
Merged

**Pull request closed without merging**
