### PR TITLE
Added Russian translation for the shortcut

### PR DESCRIPTION
**Pull request by TotalCaesar659**
Added Russian translation for the shortcut name and pop-up comment

### CODE REVIEW

**Comment by TotalCaesar659** [comment]
OK, I publish this commit under MIT license.

**Comment by guruz** [comment]
Thanks. Normally we handle translations via https://www.transifex.com/owncloud-org/owncloud/
However those desktop.in files are a special case. This is something we need to find out how to do best.

**Comment by danimo** [comment]
@DeepDiver1975 any idea how we could integrate the .desktop strings into the existing translations? maybe even without creating yet another translation project?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 any idea how we could integrate the .desktop strings into the existing translations? maybe even without creating yet another translation project?

let me think about this ....

**Comment by DeepDiver1975** [comment]
transifex is supporting this file type - http://docs.transifex.com/formats/desktop/

Let me work on this ....

**Comment by DeepDiver1975** [comment]
Superseded by https://github.com/owncloud/client/pull/4715

**Pull request closed without merging**
