### PR TITLE
Only set valid icons on top-level windows

### PR DESCRIPTION
**Pull request by erikjv**
Also warn when an icon is null.

### CODE REVIEW

**Comment by erikjv** [comment]
I hope this fixes https://sentry.io/organizations/owncloud/issues/2956248154/?project=79001

**Comment by TheOneRing** [comment]
The question is why does it fail to load the icon, thats not supposed to happen in the first place.
And well I would not expect Qt to crash in that case.

**Comment by fmoc** [comment]
I think assertions in the getters might be a better solution. There's likely a root cause to this mess...

**Comment by TheOneRing** [comment]
As discussed in chat we now expect https://github.com/owncloud/client/pull/9418 to fix this.

**Pull request closed without merging**
