### PR TITLE
Documented: unsupported server version warning message -> 2.5

### PR DESCRIPTION
**Pull request by lefherz**
like #6773, but for the correct branch :) @tboerger can you merge and deploy the docs?

### CODE REVIEW

**Comment by ho4ho** [comment]
Nextcloud check interpreted as "fighting":

> Argh they now really start fighting against each other - WTF?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847613

**Comment by lefherz** [comment]
thanks for the notice. I'll look into it.

**Comment by ho4ho** [comment]
:+1: https://alioth-lists.debian.net/pipermail/pkg-owncloud-maintainers/2019-January/003498.html

**Comment by ho4ho** [comment]
@lefherz Other :cry: :

> I think it's more a pitch of the owncloud developers for their own product

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918930#10

**Comment by ho4ho** [comment]
Message could be one reason why owncloud-client unsupported by Debian maintainer :cry: 

https://alioth-lists.debian.net/pipermail/pkg-owncloud-maintainers/2019-August/003691.html

**Pull request merged**
