### PR TITLE
Backport #4052 to 2.0

### PR DESCRIPTION
**Pull request by RealRancor**
Ref: #4052

### CODE REVIEW

**Comment by guruz** [comment]
As far as I heard there won't be a new 2.0.x, sorry.

**Comment by RealRancor** [comment]
But docs are still generated for 2.0 or are the generation of those stopped? Just wondering because https://github.com/owncloud/client/pull/4058 was also merged into 2.0.

**Comment by danimo** [comment]
@guruz the documentation for 2.0 is updated regardless, so this is fine.

**Comment by guruz** [comment]
ok, you guys are of course right.

**Pull request merged**
