### PR TITLE
Blacklist: Escalate a repeated 423 Locked to NormalError #5500

### PR DESCRIPTION
**Pull request by ckamm**
Since this targets 2.3.1 I pointed this PR at master.

We should discuss whether we also want this kind of escalation for other soft errors.

### CODE REVIEW

**Comment by ogoffart** [comment]
:+1:

**Comment by ogoffart** [comment]
Need to be merged in 2.3 then, right?

**Comment by ogoffart** [comment]
CONFLICT (content): Merge conflict in src/libsync/owncloudpropagator.cpp

**Comment by ckamm** [comment]
Merged manually as 8ef11a38c99c6a33b175f1ad792ec02b52f88d25

**Pull request closed without merging**
