### PR TITLE
[Tests-Only]Make log comment depends upon existence of logs

### PR DESCRIPTION
**Pull request by Talank**
~~Let's see if depends_on works for restricting to upload logs if GUI tests do not run.~~

The comment in GH is not created if the `comment.file` does not exist. So, I wrote a bash script to check if GUI log and server log is present before creating the comment. Ergo, if any of the log is not present then we do not create the respective link in the comment, and of no log is generated at all then we simply do not create the comment file.

### CODE REVIEW

**Comment by Talank** [comment]
depends_on GUItests does not work. It simply skips the step if GUI tests fails. Which is opposite of what we want. Alternatively, we can list other steps, such as build comment and everything depends on `clone`, `cmake`, etc.

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/10836/5/1
:boom: The GUI tests failed.\nGUI Logs: (owncloud/client/10836///guiReportUpload/index.html)
GUI Logs: (owncloud/client/10836///guiReportUpload/serverlog.log)

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/10837/5/1
:boom: The GUI tests failed.\nGUI Logs: (owncloud/client/10837///guiReportUpload/index.html)
GUI Logs: (owncloud/client/10837///guiReportUpload/serverlog.log)

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/10843/5/1
:boom: The GUI tests failed.\nGUI Logs: (https://cache.owncloud.com/public/owncloud/client/10843/guiReportUpload/index.html)
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/10843/guiReportUpload/serverlog.log)

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/10844/5/1
:boom: The GUI tests failed.\nGUI Logs: (https://cache.owncloud.com/public/owncloud/client/10844/guiReportUpload/index.html)
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/10844/guiReportUpload/serverlog.log)

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/10845/5/1
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/10845/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/10845/guiReportUpload/serverlog.log)

**Comment by Talank** [comment]
I am running only the skipped tests to see if the comment generation works as earlier.

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/10856/5/1
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/10856/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/10856/guiReportUpload/serverlog.log)

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/10857/5/1
Server Logs: (https://cache.owncloud.com/public/owncloud/client/10857/guiReportUpload/serverlog.log)

**Comment by Talank** [comment]
> Results for **GUI-tests** https://drone.owncloud.com/owncloud/client/10857/5/1 Server Logs: (https://cache.owncloud.com/public/owncloud/client/10857/guiReportUpload/serverlog.log)

I disabled html report generation, hence it only builds link for serverlog. Si, IMO, the current solution works.

**Review by individual-it — APPROVED** [review]

**Pull request merged**
