### PR TITLE
Installing doc typo

### PR DESCRIPTION
**Pull request by phil-davis**
Let me know which other branches should get backports of typos - maybe 1.8, 1.8.4, 2.0?
And are you happy for me to commit back-ported fixes directly to the old branches? Or do you want me to submit a PR for each back-ported change?
I am proof-reading the existing docs, so will submit PRs for typos that I find today. Then I guess someone will soon be updating these docs again for the 2.0 that is now in beta.

### CODE REVIEW

**Comment by guruz** [comment]
Thanks a lot.. let's keep it at master branch..

Did you send https://owncloud.org/contribute/agreement/ ? :-)

If you're in Europe end of the month, we also have the contributor conference..

**Comment by phil-davis** [comment]
Yes, I sent the contributor agreement to Frank a couple of weeks ago and he enabled the repo access stuff. I am from Australia and live in Nepal - Europe is the opposite direction!
Does the existing doc published on the web site get built from 1.8 branch?
(Like the other core developer/admin/user docs have stable7, stable8, stable8.1 branches all being published so that users can read the documentation as it applies to the version they are currently using)

**Comment by phil-davis** [comment]
Why is this showing 2.1-next milestone?
Don't we want to just fix ordinary doc typos straight away, so they get fixed in the current (or about to be) online documentation?

**Comment by guruz** [comment]
```	phil-davis  wants to merge 1 commit into master from phil-davis-installing-master```

The current version is in the ```2.0``` branch

**Comment by phil-davis** [comment]
So am I best to make pull requests against 2.0 branch?
And then the whole of 2.0 branch will be merged to master at the appropriate time.

**Comment by guruz** [comment]
yes :)

**Comment by phil-davis** [comment]
Closed in favour of https://github.com/owncloud/client/pull/3621

**Pull request closed without merging**
