### PR TITLE
Building the desktop client with KDE updated

### PR DESCRIPTION
**Pull request by ozata**

### CODE REVIEW

**Comment by ozata** [comment]
https://owncloud.org/news/interview-kde-craft-improves-owncloud-client-build-process/ Credit is due

**Comment by TheOneRing** [comment]
Hi thanks that's awesome 😄

**Comment by ozata** [comment]
> Hi thanks that's awesome 😄

Thank you actually, followed your steps.

**Comment by ozata** [comment]
This is my first contribution to an open source project, means a lot to me, thank you guys.

**Pull request merged**
