### PR TITLE
Update "..." menu documentation for 2.0

### PR DESCRIPTION
**Pull request by phil-davis**
This menu in 2.0.* now has 4 options.
The small screenshot needs updating also. @carlaschroder it is probably best if you take a new screen shot from whatever client version you have been using for screen shots. That way they will all have a consistent look.

### CODE REVIEW

**Comment by phil-davis** [comment]
Note: An updated screenshot is needed of this "..." menu, hopefully can be supplied by @carlaschroder

**Comment by carlaschroder** [comment]
@phil-davis I'm looking at the 2.0.1 (build 5446) release, and there are only three options, as in the original text. What version are you looking at?

**Comment by phil-davis** [comment]
I am on a 2.0.2 version. I guess the 4 menu options are in 2.0.2-beta1? I think it came in between 2.0.1 and 2.0.2.
If that is correct, then this documentation change needs to be "released" along with 2.0.2 - I am not sure how if that is possible for UI features that actually change with point releases of the software.

**Comment by carlaschroder** [comment]
I'm going to revert this PR & save your changes for when 2.0.2 is released. It's available from the Testing repo, but we maintain only stable release manuals. Thanks and wait until we catch up :)

**Comment by phil-davis** [comment]
No problem - I had seen 2.0.2-beta1 come out a while ago and assumed that a 2.0.2 release was imminent, so proposed this doc update. It seems that 2.0.2 has stopped at beta1 for the moment.

**Comment by carlaschroder** [comment]
yay @phil-davis 2.0.2 is released! I shall restore this update.

**Comment by carlaschroder** [comment]
https://github.com/owncloud/client/pull/3982

**Comment by phil-davis** [comment]
:+1:

**Pull request merged**
