### PR TITLE
templates > .github and create release_template

### PR DESCRIPTION
**Pull request by michaelstingl**
I would like to have the release steps under version control to constantly improve the process. And we could put all templates to the .github folder same as it's in the core repo.

@guruz @ogoffart @SamuAlfageme What do you think?

**Open tasks:**

- [ ] Remove redundant wiki page [owncloud/client/Release Checklist Template](https://github.com/owncloud/client/wiki/Release%20Checklist%20Template)
- [ ] Merge with "Squash and merge" option

### CODE REVIEW

**Comment by ogoffart** [comment]
There are many links to the issue_template.md that points to it in the root location.
So we must move that file carefully. For example there is a link in CONTRIBUTING.md that needs to be updated.
There might be more  (there are links in many issue but i gues they need not to be changed)

**Comment by michaelstingl** [comment]
@ogoffart Good point. I could copy the file for the start to make migration smoother.

**Comment by guruz** [comment]
I wanted to revise the release template a bit. Shall I do this before or after this is merged? Maybe after is better..

**Comment by michaelstingl** [comment]
@guruz Both fine for me. You can update the wiki page, and I will then update the PR…

**Pull request merged**
