### PR TITLE
Update the link to the ownCloud.org download page in install guide

### PR DESCRIPTION
**Pull request by settermjd**
### Relates To 

https://github.com/owncloud/documentation/issues/3714.

### CODE REVIEW

**Comment by hurradieweltgehtunter** [comment]
I don't think so. Clients are still downloadable on oc.com 
I meant only updating the oc.org download links

**Comment by settermjd** [comment]
@SamuAlfageme, better?

**Comment by SamuAlfageme** [comment]
@settermjd I meant moving the variable with the full URL to the theme locations:

- https://github.com/owncloud/documentation/tree/master/_shared_assets/themes/owncloud_com for the EE documentation
- https://github.com/owncloud/documentation/tree/master/_shared_assets/themes/owncloud_org for the community 

This could allow to maintain both links working depending on which URL you're accessing the documents from:

- https://doc.owncloud.org/desktop/latest/installing.html will point to https://owncloud.org/download/#owncloud-desktop-client
- https://doc.owncloud.com/desktop/latest/installing.html to https://owncloud.com/install/#desktop

So both websites are not coupled (we might want to offer different sw versions for community and EE users).

**Comment by ogoffart** [comment]
I think it is better if the url are full URL, bezcause someone might be reading the documentation not online.

**Pull request closed without merging**
