### PR TITLE
Fix debug symbols on macOS

### PR DESCRIPTION
**Pull request by dschmidt**

### CODE REVIEW

**Comment by guruz** [comment]
> Do not run macdeployqt.py from CMake. 

How does make install work then?

**Comment by dschmidt** [comment]
The CI Script calls it directly. The other changes I did require that the script is run after *all* targets are installed. 

I need to know which files have been built by ourselves so I can run dsymutil on them. And as the script does not get passed the target it's enough to run it once in the end.
Also I would consider pulling in deps at install time an antipattern - this concrete scenario is a good example why.

**Comment by dschmidt** [comment]
... and as the script is not target specific but run on the whole bundle it's enough to run it once after all is installed instead of running it trice after every application target is installed.

**Comment by guruz** [comment]
Hm would have been better to also check ENABLE_CRASHREPORTS always before CopyDSYM,

**Pull request merged**
