### PR TITLE
Migration from 2.4: fallback to move file by file if directory move failled

### PR DESCRIPTION
**Pull request by ogoffart**
This can happen if the directory already exist because, say, it was
created by another program which save its file in the same directory

### CODE REVIEW

**Comment by ogoffart** [comment]
Need further testing...

**Comment by guruz** [comment]
(For the record, I heard it was this other program: https://owncloud.com/outlook-plug-in/ )

**Comment by guruz** [comment]
Code looks OK, I need to actually test it.
So we think it's ok to keep the old directory around empty in case of the fallback-renames? (i think it's ok)

**Comment by ogoffart** [comment]
I tested this on linux only.

**Comment by ogoffart** [comment]
I also tested on windows, and it works.  

(I removed all owncloud configuration, ran and configured 2.4.2.
Then tested the upgrade to 2.5.1 with this patched. It worked fine.  Moved the folder back to its 2.4 place, but added an empty folder ownCloud in the new location.  Ran again 2.5.1, and it migrated fine again.)

@guruz :  merge?

**Comment by guruz** [comment]
(i didnt test the actual PR yet, this is what I found when preparing to test:)
There is an annoying issue when removing the new location directory and then trying to use 2.4
It doesnt save the configuration at all:
```
/Users/guruz/Library/Application Support/ownCloud: broken symbolic link to /Users/guruz/Library/Preferences/ownCloud
```
Not sure if this is something we should fix.

**Comment by ogoffart** [comment]
> Not sure if this is something we should fix.

No, that's not something we should fix

**Comment by guruz** [comment]
Directory looked like this:
```
guruz@mgmbp2018 documentation $ ls -l '/Users/guruz/Library/Preferences/ownCloud'    '/Users/guruz/Library/Application Support/ownCloud'
/Users/guruz/Library/Application Support/ownCloud:
total 16
-rw-r--r--  1 guruz  staff   382B Oct 24 14:10 cookies0.db
-rw-r--r--  1 guruz  staff   362B Oct 24 14:10 owncloud.cfg

/Users/guruz/Library/Preferences/ownCloud:
total 16
-rw-r--r--  1 guruz  staff   600B Oct 24 14:08 cookies0.db
-rw-r--r--  1 guruz  staff   913B Oct 24 14:06 owncloud.cfg.backup_20181024_140642
```
(properly no owncloud.cfg like requested by your if())

Message when running your branch:
```
gui.application: Migrating old config from "/Users/guruz/Library/Application Support/ownCloud" to "/Users/guruz/Library/Preferences/ownCloud"
gui.application: Failed to move the old config file to its new location ( "/Users/guruz/Library/Application Support/ownCloud" to "/Users/guruz/Library/Preferences/ownCloud" )
gui.application: Will move the independent files ("cookies0.db", "owncloud.cfg")
gui.application: Fallback move of  "cookies0.db" also failed
```
Then it looks like this:
```
/Users/guruz/Library/Application Support/ownCloud:
total 8
-rw-r--r--  1 guruz  staff   600B Oct 24 14:10 cookies0.db

/Users/guruz/Library/Preferences/ownCloud:
total 32
-rw-r--r--  1 guruz  staff   600B Oct 24 14:08 cookies0.db
-rw-r--r--  1 guruz  staff   385B Oct 24 14:10 owncloud.cfg
-rw-r--r--  1 guruz  staff   913B Oct 24 14:06 owncloud.cfg.backup_20181024_140642
-rw-r--r--  1 guruz  staff   362B Oct 24 14:10 owncloud.cfg.backup_20181024_141054
```

Starts properly with the migrated owncloud.cfg from old dir. cookies0.db failed is OK I guess.

So I would +1 this if you change the phrase `Failed to move the old config file to its new location` to be about the directory (as the first move attempt is about the directory not about the file).

**Pull request merged**
