### PR TITLE
Haiku port

### PR DESCRIPTION
**Pull request by mmuman**
I had this already working some months ago, but of course I had to rebase and fix stuff again. Also, I was waiting for my PR on qtkeychain to be merged.

It builds and seems to run, but just hung on me, while it didn't on the initial port, so I will have to investigate.

I wrote a [HaikuPorts recipe](https://github.com/haikuports/haikuports/commit/83f08706253969a6cf4e330dbc30e6a85c82f953), but there are still some policy warnings, since the paths that are passed to CMake are not respected on install (we don't have `include/` but `develop/headers/[x86/]`, no `share/` but `data/` instead…).

Comments welcome.

### CODE REVIEW

**Comment by mmuman** [comment]
Of course windows doesn't have `sys/time.h`…

**Comment by ogoffart** [comment]
Thank you for the patch.

Everything looks good to me, although i did not really look the haiku specific part in details.

**Comment by mmuman** [comment]
> cla-assistant would like additional permissions to:
> Gists: Read and write access
> Organizations and teams: Read-only access
> Commit statuses: Read and write access
> Personal user data: Email addresses (read-only)
> Repository webhooks and services: Read and write access

Ok, email, but why the rest? Is there any valid reason or is it just a default configuration that nobody cared to fix?

**Comment by vaskas** [comment]
@mmuman since Haiku is now on Qt 5.15 this commit is needed to compile: https://github.com/owncloud/client/commit/dea019eff62c728784c63ee0f88b61c485284e17

As of today it's not in a release yet (2.6.3 comes without it).

**Comment by mmuman** [comment]
Guess I'll have to rebase.
I'd still like some explanation on the cla bot permissions meanwhile…

**Comment by mmuman** [comment]
Just rebased.

I still have some failed tests though, including some crashes, or rather aborts, not sure why yet. Btw, when tests like ChunkingNg crash, they leave like a GB of stuff in /tmp …

**Comment by DeepDiver1975** [comment]
looks old and outdated .... closing - reopen if there is any progress. THX

**Comment by mmuman** [comment]
Well FWIW somebody finished my nextcloud client port…

**Pull request closed without merging**
