### PR TITLE
updates for 2.1 release

### PR DESCRIPTION
**Pull request by carlaschroder**
This is the first batch of updates for 2.1, some updated screenshots and descriptions.

### CODE REVIEW

**Comment by carlaschroder** [comment]
@danimo @dragotin

**Comment by danimo** [comment]
:+1:

**Comment by dragotin** [comment]
@carlaschroder do you realized that the "Add Account" button, that was in the General tab before, was moved to this toolbox-button on the account page. This has the implication that, if the wizard is closed, people need to left-click on the tray icon to get the configuration dialog started again. No way to do it from the settings dialog currently.

Not sure if that is a good solution, but not blocking 2.1 currrently I'd say.

**Comment by carlaschroder** [comment]
thx @dragotin, I'll add a section highlighting how to add new accounts.

**Pull request merged**
