### PR TITLE
Fixing typos in brazilian portuguese translation.

### PR DESCRIPTION
**Pull request by andrepontesmelo**

### CODE REVIEW

**Comment by ogoffart** [comment]
I believe this needs to be contributed on transifex. 

@DeepDiver1975  right?

**Comment by andrepontesmelo** [comment]
I tried Transifex, but this language is 100% translated, and when I try to open the translations, it gives me this server error: https://goo.gl/KsPsfY

**Comment by DeepDiver1975** [comment]
> I believe this needs to be contributed on transifex.

yes

**Comment by DeepDiver1975** [comment]
> I tried Transifex, but this language is 100% translated, and when I try to open the translations, it gives me this server error: https://goo.gl/KsPsfY

@andrepontesmelo are you member of the pt translation team? Maybe the translation is already reviewed has to be changed by a reviewer or one of the team coordinators. Please discuss this on transifex

**Pull request closed without merging**
