### PR TITLE
allow displayname instead of display-name

### PR DESCRIPTION
**Pull request by jnweiger**
Seen in https://github.com/owncloud/product/issues/181#issuecomment-680223599
Please check which one is correct.

### CODE REVIEW

**Comment by TheOneRing** [comment]
That indicates a server bug I guess.
@butonic

**Comment by butonic** [comment]
It is, but this would make the client a little more forgiving. Because the ocs endpoints in oc10 cannot even agree on how to spell things: https://github.com/owncloud/product/issues/181#issuecomment-685789391

The server would like to fix this and make it `displayname` everywhere ... but clients should allow that by checking both ... :chicken: :egg: problem ...

**Comment by TheOneRing** [comment]
Ah ok

**Review by TheOneRing — APPROVED** [review]

**Review by TheOneRing — CHANGES_REQUESTED** [review]
Please target 2.7

**Pull request merged**
