### PR TITLE
Windows: Integrate with the navigation pane

### PR DESCRIPTION
**Pull request by jturcotte**
This is only activated on Windows 10 and later and only include the navigation pane part of
https://msdn.microsoft.com/en-us/library/windows/desktop/dn889934%28v=vs.85%29.aspx

The "sync root provider" section still has to be done, which I suspect is what allows Microsoft
Office to display the cloud storage entry in its file management dialog.

Issue #5295

### CODE REVIEW

**Comment by ogoffart** [comment]
Maybe create a new WindowPaneHelper class, so you can move the code away from folderman?

**Comment by SamuAlfageme** [comment]
@jturcotte this is super cool! 🔝 

Screenshots for ref:

<p align="center">
  
</p>

**Comment by michaelstingl** [comment]
@CorneelDragon @haukman FYI ^

**Comment by CorneelDragon** [comment]
@michaelstingl  Looks great! Thanks for the work and the update 👍

**Comment by haukman** [comment]
awesome! :) Thanks @jturcotte

**Comment by jturcotte** [comment]
@ogoffart Moved to a `NavigationPaneHelper` object in `FolderMan`.

**Pull request merged**
