### PR TITLE
Backport #3892 to 1.8

### PR DESCRIPTION
**Pull request by RealRancor**
Ref: #3892

### CODE REVIEW

**Comment by danimo** [comment]
I already cherry-picked this :)

**Comment by RealRancor** [comment]
Yes, only for 2.0 but not for 1.8:

https://doc.owncloud.org/desktop/1.8/faq.html#faq

:-)

**Comment by danimo** [comment]
Ah. 1.8 branch is closed when it comes to documentation, i.e. the documentation is no longer being regenerated. I should have written "backported to all _relevant_ branches" :)

**Comment by RealRancor** [comment]
Ahhh, good to know. Thanks for the info.

**Pull request closed without merging**
