### PR TITLE
SocketAPI: Use different pipe name #4977

### PR DESCRIPTION
**Pull request by ckamm**
Named pipe names that contain backslashes sometimes lead to problems.

### CODE REVIEW

**Comment by dragotin** [comment]
Any rationale why this will help?

**Comment by guruz** [comment]
@dragotin https://github.com/owncloud/client/issues/4977#issuecomment-227656955

**Comment by guruz** [comment]
@jturcotte @danimo After reviewing/merging could you update the binary submodule and create a nightly for @ArthurChiao to test?

**Comment by danimo** [comment]
:-1: Do not apply magic thinking. Backslashes are common in pipe names.

**Comment by guruz** [comment]
@danimo This is not magic thinking. Check the other bug report, @ArthurChiao tested this.

```The pipe name string specified by PipeName can include any character other than a backslash, including numbers and special characters. ```
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365783(v=vs.85).aspx

**Comment by jturcotte** [comment]
See also http://stackoverflow.com/questions/3571422/can-named-pipe-names-have-backslashes

According to the question and answer, it seems like it could fail of something creates a pipe with the name up to the first slash, which happens to be the old pipe name. So an older version of the client would prevent the new version from creating its pipe, even though the new one would have the extension installed, leaving neither of them working.

Not sure if that's the issue that the user is seeing though.

**Comment by jturcotte** [comment]
Humm reading https://github.com/owncloud/client/issues/4977#issuecomment-227412471, he built the windows client himself and commenting out the backslash from the path does make `mkpath` return faster.

The question is why are we trying to do mkpath on `\\.\pipe\ownCloud\username` on windows and set permissions?

But even then, replacing that backslash with a dash is likely going to fix it too according to his investigation. So since I don't see an advantage to use a backslash over a dash, ideally we'd do both removing that mkpath on windows, and remove the backslash from the pipename to avoid mixed client/shellintegration versions to prevent newer versions from creating their pipe.

**Comment by jturcotte** [comment]
Tested the change and it doesn't break anything, I'll merge this pull request and create a new one to update binaries.

**Comment by ArthurChiao** [comment]
Tested with `ownCloud-2.2.3.6203-nightly20160627-setup.exe`, problem [#4977](https://github.com/owncloud/client/issues/4977#issuecomment-227412471) is fixed.

**Pull request merged**
