### PR TITLE
Add the account context menu to the account buttons

### PR DESCRIPTION
**Pull request by TheOneRing**
image

### CODE REVIEW

**Review by michaelstingl — APPROVED** [review]
yeah, works for me 👍

**Comment by dragotin** [comment]
Tbh, I dislike. Is that in addition to the (also not optimal) combo box? If the plan is to remove the combo, which would make sense, I think the account avatar "buttons" would need some visual indication that there is an menu to open, and in that case it should not be right click.

More like this (example): 
ksnip_20210728-151941

**Comment by TheOneRing** [comment]
I just happend to click on the Avatar as I kind of expected options to be available especially if you have multiple.
Yes they are basically buttons but the way we use them is not how buttons are used.

**Comment by erikjv** [comment]
I have to say that I'd never guess that right-clicking on one of those toolbar buttons would actually do something. I would just copy the ... button that the folder has and use it instead of the account combo.

**Comment by TheOneRing** [comment]
You are all right, I guess we should kill the old  button and move the menu to the account button?

**Comment by fmoc** [comment]
Yep, sounds like a good idea.

Should the PR target 2.9 already?

**Pull request closed without merging**
