### PR TITLE
[tests-only] Bump owncloud test middleware to version 1.6.0

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
bump owncloud test middleware to version 1.6.0

## Related
part of https://github.com/owncloud/owncloud-test-middleware/issues/114

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11594/6/1

<details>


</details>

**Comment by kiranparajuli589** [comment]
ci failed at `cmake` https://drone.owncloud.com/owncloud/client/11594/6/12, build restarted

**Comment by kiranparajuli589** [comment]
again failed at `cmake`. @Talank @saw-jan can you guys have a look here.

**Comment by Talank** [comment]
> again failed at `cmake`. @Talank @saw-jan can you guys have a look here.
ok, I'll take a look

**Review by saw-jan — APPROVED** [review]
LGTM

**Pull request merged**
