### PR TITLE
sqlite: Set exclusive locking_mode to avoid WAL issues

### PR DESCRIPTION
**Pull request by ckamm**
Please double check that this is safe to do for a patch release. I think it is.

For #6881

### CODE REVIEW

**Comment by guruz** [comment]
Are we really sure this works for our multi-threaded access? (vs multi-process)

https://www.sqlite.org/wal.html

> Specialized applications for which the default implementation of shared memory is unacceptable can devise alternative methods via a custom VFS. For example, if it is known that a particular database will only be accessed by threads within a single process, the wal-index can be implemented using heap memory instead of true shared memory.

Doesnt this kind of imply we need a wal-index if we want multi-thread?

>  If the VFS does not support shared-memory methods, then the attempt to open a database that is already in WAL mode, or the attempt convert a database into WAL mode, will fail. 

Hm.

**Comment by guruz** [comment]
(see also my comments on https://github.com/owncloud/client/issues/6881#issuecomment-453145542 )

**Comment by ckamm** [comment]
By default I'd have assumed that an exclusive locking_mode on an sqlite connection prevents other connections, even in the same process. The bugreport suggests otherwise but I haven't found explicit mention of it in the documentation.

In the client all db access goes through a single `SyncJournalDb` instance and thus one connection. (The separate connection in `SocketApi` is gone)

Poking around a bit I see that the shared-cache mode (https://www.sqlite.org/sharedcache.html) allows multiple connections in the same process to share a cache. According to the source code that seems to relate to the sqlite pager, where the locking is located. It's plausible that this mode would allow multiple connections in the process (if we needed it).

The quote about WAL mode opens failing if there's no shared-memory methods is about normal locking_mode. With exclusive locking mode we'd get a heap wal.

**Comment by guruz** [comment]
You kind of have me convinced. I'd +1.
But we can wait a bit more for @ogoffart to agree.

**Pull request merged**
