### PR TITLE
zsync: use larger rolling hash size to avoid conflicts

### PR DESCRIPTION
**Pull request by ckamm**
This PR is based on top of https://github.com/owncloud/client/pull/6389 and has only one commit https://github.com/owncloud/client/commit/15aff7b0dd188bb9bc8d36c9e7d243b56af2697c. It also depends on https://github.com/ahmedammar/zsync/pull/2

@ahmedammar

### CODE REVIEW

**Comment by ckamm** [comment]
The zsync PR has to merge before this PR can be updated and merged.

**Comment by ckamm** [comment]
This PR only works in conjunction with my zsync patch. So the steps are
* merge zsync PR
* update this PR to have the git submodule point the final sha1 in the zsync repo
* merge this PR

**Comment by ahmedammar** [comment]
zsync PR merged. Thanks @ckamm for putting all this work in, great to know this is all in capable hands!

**Comment by ckamm** [comment]
This PR needs to be rebased onto delta-sync and the zsync submodule sha1 needs to be updated once https://github.com/ahmedammar/zsync/pull/3 is merged

**Comment by ckamm** [comment]
@ogoffart @ahmedammar All is now in order and jenkins passes - does this look good to you?

**Comment by ahmedammar** [comment]
Looks great! I've been following your commits, thanks!

**Pull request merged**
