### PR TITLE
Delta-sync upload fixes

### PR DESCRIPTION
**Pull request by ckamm**
I still need to add a bunch of unit tests but manual upload tests now pass much more reliably for me.

@mrow4a Possibly rerun your tests with this branch to verify.

@ahmedammar

### CODE REVIEW

**Comment by ogoffart** [comment]
TestChunkingNG::testResume is failling but i don't know if it is a regression.

Otherwise, just merge it.

**Comment by ckamm** [comment]
@ogoffart It's a regression I'll have to investigate.

**Comment by mrow4a** [comment]
are you sure it is not related with assert fix?

**Comment by ckamm** [comment]
Fixed. The issue was that I adjusted `_sent` to only be adjusted *after* PUT jobs finish instead of at the start - but I forgot to change the progress reporting to match. All tests pass for me now.

**Comment by mrow4a** [comment]
I still have problems with delta sync when I manualy change the file - no idea what is wrong. 

```
openssl rand 33000000 -base64 -out test.txt
less test.txt 
nano test.txt - change some line or characters inside
```
delta-test-1

@ahmedammar

**Comment by mrow4a** [comment]
Tried `bin/smash -t 2 lib/test_basicSync.py` - this test checks handling of the conflicts in ownCloud - unfortunetelly client freezes and goes into some strange loop. The last log I can see is 

```
03-11 16:12:22:271 [ info sync.networkjob ]:	OCC::PUTFileJob created for "http://localhost/delta" + "" "OCC::PropagateUploadFileNG"
03-11 16:12:22:315 [ info sync.networkjob.mkcol ]:	MKCOL of QUrl("http://test_basicSync@localhost/delta/remote.php/dav/uploads/test_basicSync/3953323096") FINISHED WITH STATUS QNetworkReply::NetworkError(NoError) ""
03-11 16:12:22:344 [ info sync.accessmanager ]:	3 "" "http://test_basicSync:test@localhost/delta/remote.php/dav/uploads/test_basicSync/3953323096/0000000000000000" has X-Request-ID "f126b119-d4f3-4943-bb4c-20d61fbfd298"
03-11 16:12:22:344 [ info sync.networkjob ]:	OCC::PUTFileJob created for "http://localhost/delta" + "" "OCC::PropagateUploadFileNG"
03-11 16:12:23:253 [ info sync.networkjob.put ]:	PUT of "http://test_basicSync:test@localhost/delta/remote.php/dav/uploads/test_basicSync/3397897757/0000000010000000" FINISHED WITH STATUS QNetworkReply::NetworkError(NoError) "" QVariant(int, 201) QVariant(QString, "Created")
03-11 16:12:23:253 [ info sync.propagator.upload ]:	Chunked upload of 40000000 bytes took 983 ms, desired is 60000 ms, expected good chunk size is 2441505595 bytes and nudged next chunk size to  100000000 bytes
03-11 16:12:23:254 [ info sync.accessmanager ]:	6 "MOVE" "http://test_basicSync:test@localhost/delta/remote.php/dav/uploads/test_basicSync/3397897757/.file.zsync" has X-Request-ID "f5f70287-6a34-4273-aefd-b4201339ba6a"
03-11 16:12:23:254 [ info sync.networkjob ]:	OCC::MoveJob created for "http://localhost/delta" + "" "OCC::PropagateUploadFileNG"
03-11 16:12:23:603 [ info sync.networkjob.put ]:	PUT of "http://test_basicSync:test@localhost/delta/remote.php/dav/uploads/test_basicSync/3953323096/0000000000000000" FINISHED WITH STATUS QNetworkReply::NetworkError(NoError) "" QVariant(int, 201) QVariant(QString, "Created")
03-11 16:12:23:603 [ info sync.propagator.upload ]:	Chunked upload of 50000000 bytes took 1260 ms, desired is 60000 ms, expected good chunk size is 2380952380 bytes and nudged next chunk size to  100000000 bytes
03-11 16:12:23:608 [ info sync.accessmanager ]:	3 "" "http://test_basicSync:test@localhost/delta/remote.php/dav/uploads/test_basicSync/3953323096/.zsync" has X-Request-ID "17483a5b-2281-44ee-ba97-5782b95a210b"
03-11 16:12:23:609 [ info sync.networkjob ]:	OCC::PUTFileJob created for "http://localhost/delta" + "" "OCC::PropagateUploadFileNG"
03-11 16:12:23:973 [ info sync.networkjob.put ]:	PUT of "http://test_basicSync:test@localhost/delta/remote.php/dav/uploads/test_basicSync/3953323096/.zsync" FINISHED WITH STATUS QNetworkReply::NetworkError(NoError) "" QVariant(int, 201) QVariant(QString, "Created")
03-11 16:12:23:973 [ info sync.accessmanager ]:	6 "MOVE" "http://test_basicSync:test@localhost/delta/remote.php/dav/uploads/test_basicSync/3953323096/.file.zsync" has X-Request-ID "0c2fb1fe-8f10-445d-8389-45a2e24e2693"
03-11 16:12:23:974 [ info sync.networkjob ]:	OCC::MoveJob created for "http://localhost/delta" + "" "OCC::PropagateUploadFileNG"
03-11 16:12:25:670 [ info sync.networkjob.move ]:	MOVE of QUrl("http://test_basicSync@localhost/delta/remote.php/dav/uploads/test_basicSync/3397897757/.file.zsync") FINISHED WITH STATUS QNetworkReply::NetworkError(NoError) ""
03-11 16:12:25:670 [ info sync.database ]:	Updating file record for path: "TEST_FILE_ADDED_LOSER.dat" inode: 8594251986 modtime: 1520781138 type: 0 etag: "d30eefdffb8aa5f724f19bd8c3b835eb" fileId: "00000333ocosxbmlf31g" remotePerm: "" fileSize: 50000000 checksum: "SHA1:27dca84b8b251f2bba072dc779605ce4428c68b9"
03-11 16:12:25:671 [ info sync.propagator ]:	Completed propagation of "TEST_FILE_ADDED_LOSER.dat" by OCC::PropagateUploadFileNG(0x7f82dac5ffc0) with status 4
03-11 16:12:26:678 [ info sync.networkjob.move ]:	MOVE of QUrl("http://test_basicSync@localhost/delta/remote.php/dav/uploads/test_basicSync/3953323096/.file.zsync") FINISHED WITH STATUS QNetworkReply::NetworkError(NoError) ""
03-11 16:12:26:678 [ info sync.database ]:	Updating file record for path: "TEST_FILE_MODIFIED_LOSER.dat" inode: 8594251912 modtime: 1520781138 type: 0 etag: "28f62f3012dfdb22397372fd466cb8e5" fileId: "00000290ocosxbmlf31g" remotePerm: "WDNVRz" fileSize: 50000000 checksum: "SHA1:27dca84b8b251f2bba072dc779605ce4428c68b9"
03-11 16:12:26:678 [ info sync.propagator ]:	Completed propagation of "TEST_FILE_MODIFIED_LOSER.dat" by OCC::PropagateUploadFileNG(0x7f82dd036e10) with status 4
03-11 16:17:24:067 [ warning sync.networkjob ]:	Network job timeout QUrl("/TEST_FILE_MODIFIED_BOTH.dat")
03-11 16:17:24:067 [ warning sync.networkjob.get ]:	Timeout QUrl("/TEST_FILE_MODIFIED_BOTH.dat")
03-11 16:17:24:067 [ warning sync.networkjob ]:	Network job timeout QUrl("/TEST_FILE_ADDED_BOTH.dat")
03-11 16:17:24:067 [ warning sync.networkjob.get ]:	Timeout QUrl("/TEST_FILE_ADDED_BOTH.dat")
```

This is also the last thing before long hang:
delta-test-4

**Comment by mrow4a** [comment]
Tried `bin/smash -t 1 lib/test_deltamove.py` and `bin/smash -t 0 lib/test_deltamove.py` which were most important for me - as this passes, I am happy enough  - conflict resolution is next step to look. 

I also confirmed, that delta worked correctly - and did delta

test-delta-5

**Comment by mrow4a** [comment]
Additionaly, please note that if I move the file - all zsync metadata gets removed and GET will fetch whole file.

**Comment by mrow4a** [comment]
Are you sure you run cmd with --deltasync flag?

**Comment by ckamm** [comment]
For the basic test yes (so we do indeed need more information about that parse error), but not for the smashbox test. With the flag I can reproduce the errors on `test_basicSync -t 2`.

**Comment by ckamm** [comment]
That took some digging! Here's why zsync gets stuck with the particular test data:
- zsync compares rolling checksums at each possible file offset and does an expensive checksum only if the rolling checksums match
- but for files composed entirely of '1' or '2' and the 1MB blocksize the rolling checksum is identical at each offset, so it runs the expensive checksum for each possible block - which takes forever
- the rolling checksum is identical for each block here because in the update equation a core part of it is a 2-byte value updated with `c * blocksize`. But since `blocksize & 0xFFFF == 0` that just does nothing.
- this is a parameter-validation bug in zsync: it's command line help suggests 4kb and 8kb as potential block sizes, the 1mb size we use is probably untested

We either need smaller block sizes or to adjust the rolling checksum. Just increasing its width might already suffice.

@ogoffart I think that fix is independent of this PR.

 @ahmedammar

**Comment by mrow4a** [comment]
👍

**Comment by ckamm** [comment]
A simpler restatement of the problem:

For files where every byte has value `d` and the block size is `s` the rolling checksum compoents will be `(d * s) mod 2^16` and `(d * s * (s + 1) / 2) mod 2^16`. If `s = 2^n for n >= 16` then both checksum components will  be 0 for any value of `d`.

I can actually reproduce this particular problem with rsync!

```
mkdir d1
mkdir d2
mkdir sync
dd if=/dev/zero  bs=1024 count=2048 | tr "\000" '1' > d1/foo
dd if=/dev/zero  bs=1024 count=2048 | tr "\000" '2' > d2/foo

rsync --stats --no-whole-file --block-size=131072 d1/* sync # initial sync
rsync --stats --no-whole-file --block-size=131072 d2/* sync # hangs
```

Note that 131072 is 2^17 and the largest block size that rsync allows. Probably for good reason? But since it's larger than 2^16 it already breaks with this particular test data.

**Pull request merged**
