### PR TITLE
Adding Norwegian translation to Client

### PR DESCRIPTION
**Pull request by vidaren**
This is to add Norwegian translation of the desktop client.

### CODE REVIEW

**Comment by danimo** [comment]
Thanks! Do you also have according translations for the Windows installer? (located at client-installer in transifex)?

**Comment by vidaren** [comment]
I can't find client-installer, do you mean Client NSIS? I have been doing the translations in Client NSIS (at 100% now), but I have not tested them. Is Norwegian active in that installer already? And can I test Norwegian on an English Windows installation?

**Comment by danimo** [comment]
> do you mean Client NSIS

Yes

> Is Norwegian active in that installer already?

No. This needs to be added to https://github.com/owncloud/client/blob/master/cmake/modules/NSIS.template.in#L165

> And can I test Norwegian on an English Windows installation?

Only if you can build it yourself, i.e. not out of the box.

**Comment by vidaren** [comment]
I assume Norwegian must be added to [admin/win/nsi/l10n/.tx/config](https://github.com/owncloud/client/blob/master/admin/win/nsi/l10n/.tx/config) too?
Let's say I'm willing to give this a try. How can I build the installer for testing my Norwegian translations on English Windows? https://doc.owncloud.org/desktop/1.8/building.html mentions two methods. Do I need to cross-compile on openSUSE or can the installer be built on Windows?

**Comment by danimo** [comment]
It probably cannot be built easily on Windows, but if you say it's at a 10% I can try to add it.

**Comment by vidaren** [comment]
Yes, translations are 100%. I just ran through them and it seems quite safe to enable Norwegian. My only concern is that a few strings are longer than English and I don't know if they'll be truncated or mess up the layout.

**Comment by danimo** [comment]
@vidaren Please try http://download.owncloud.com/desktop/daily/ownCloud-1.8.2.5104-nightly20150525-setup.exe

**Comment by danimo** [comment]
@vidaren Note this is only supposed to show a norwegian installer (for Norwegian Windows). The app itself is not yet translated, because your merge was targetting master. I have now cherry-picked it to 1.8.

**Comment by vidaren** [comment]
@danimo The installer you linked shows in English both on Norwegian and Englisth Windows. I picked ownCloud-1.8.2.5106-nightly20150525-setup.exe instead, and that shows in Norwegian. But the client installed by it shows in English on Norwegian Windows.
The installer looks quite good in Norwegian, just one truncated string on the first page. I did not test error situations though.

**Comment by vidaren** [comment]
@danimo For the record, I confirm that the current nightly builds produce a Norwegian installer, installing a Norwegian client, on Norwegian Windows. Mission ackomplished.

**Pull request merged**
