### PR TITLE
[do-not-merge] debugging folder delete test that failed in nightly builds

### PR DESCRIPTION
**Pull request by sushmita56**

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11612/6/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11612/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/11612/guiReportUpload/serverlog.log)
Screenshots:
- [Delete_a_folder.png](https://cache.owncloud.com/public/owncloud/client/11612/guiReportUpload/screenshots/Delete_a_folder.png)

**Comment by Talank** [comment]
I did some debugging and my findings are as follows:
- If there is only one folder in the client sync folder and if it is deleted then a conformation message appears. If we confirm that we wanna delete the only folder, then the sync becomes successful. 
- However, if the desktop client is not closed properly, between deletion and creation of a user with same credentials, then while deleting the only one folder in client sync directory, the conformation message do not appear. And the deletion activity is not synced until we trigger the force sync.

### Screenshot
In the gif, I have captured the following activity.
- Run the script [folder-delete-test.zip](https://github.com/owncloud/client/files/8705787/folder-delete-test.zip)
- When the password field appears, enter the password "1234", and press ENTER
- wait for script to continue execution until a delete conformation wizard appears
- Click on "Remove all files"
- And see the result
    - if there is no exception then the delete activity is synced successfully.
    - if there is an exception with message  "Folder deletion failed" then the sync is not successful and the issue is reproduced
    **Note** I did not close the client manually, so the issue has been reproduced in 2nd run. If you close the client after each execution of the script, the issue will not be reproduced.

folder_delete_reproduce

**Comment by gabi18** [comment]
I will have a look here next week - at the moment we are very busy with the client 3.0.0 alpha release.

**Comment by Talank** [comment]
This test has been skipped in master, as a lot of other test also fails. REF: https://github.com/owncloud/client/issues/9733

I will close this PR for now, since we will be concentrating on master. We can reopen it if this test also fails on master later.

**Comment by Talank** [comment]
This test is intermittently failing in master as well 
REF: https://github.com/owncloud/client/pull/9767#issuecomment-1144769542

> Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12005/6/1
>
> :boom: The GUI tests failed.
>
> GUI Logs: https://cache.owncloud.com/public/owncloud/client/12005/guiReportUpload/index.html
>
> <details>
> 
> Server Logs: https://cache.owncloud.com/public/owncloud/client/12005/guiReportUpload/serverlog.log
>
> Screenshots:
> - [Delete_a_folder.png](https://cache.owncloud.com/public/owncloud/client/12005/guiReportUpload/screenshots/Delete_a_folder.png)
>
> </details>
>
>
>

**Comment by sushmita56** [comment]
Failed again! https://github.com/owncloud/client/issues/9625#issuecomment-1181289758

**Comment by sushmita56** [comment]
The respective issue has been closed, so closing here the PR too. It can be reopened for debugging purposes if the issue appears again.

**Pull request closed without merging**
