### PR TITLE
Windows: Enable us to support sync root path > 260 char

### PR DESCRIPTION
**Pull request by TheOneRing**

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/13222/6/1

<details>


</details>

**Review by fmoc — APPROVED** [review]

**Review by fmoc — CHANGES_REQUESTED** [review]
Please see my previous review comment.

**Review by fmoc — APPROVED** [review]

**Comment by HanaGemela** [comment]
Works only without VFS

**Comment by HanaGemela** [comment]
With VFS follow https://github.com/owncloud/client/pull/10136 to make it work as well

**Comment by TheOneRing** [comment]
> Try to sync a file which root path is > 260 char on Windows without VFS. That should work. With VFS there should be a nice error handling

Not in 3.0

**Comment by saw-jan** [comment]
> Try to sync a file which root path is > 260 char on Windows without VFS. That should work. With VFS there should be a nice error handling

@HanaGemela With or without VFS, the file with root path > 260 chars gets synced.
 Syncing file:
 `thisfilehascharacterslongerthantwohundredandsixty/thisfilehascharacterslongerthantwohundredandsixty/thisfilehascharacterslongerthantwohundredandsixty/thisfilehascharacterslongerthantwohundredandsixty/thisfilehascharacterslongerthantwohundredandsixty/thisfilehascharacterslongerthantwohundredandsixty/afile.txt`

**Comment by TheOneRing** [comment]
Same as https://github.com/owncloud/client/pull/10136#issuecomment-1316612862 please test a long path to a sync root not a synced file.

**Comment by saw-jan** [comment]
> Same as [#10136 (comment)](https://github.com/owncloud/client/pull/10136#issuecomment-1316612862) please test a long path to a sync root not a synced file.

With or without the VFS, the long sync root path can be synced without changing system behavior.

**Comment by saw-jan** [comment]
Steps to test:
1. Create long path > 260 chars in the windows system (use terminal like `git bash` or https://github.com/PowerShell/PowerShell/releases)
E.g: `C:/thisfilehascharacterslongerthantwohundredandsixty/thisfilehascharacterslongerthantwohundredandsixty/thisfilehascharacterslongerthantwohundredandsixty/thisfilehascharacterslongerthantwohundredandsixty/thisfilehascharacterslongerthantwohundredandsixty/thisfilehascharacterslongerthantwohundredandsixty/ownCloud`
2. Desktop client: Add account with VFS disabled and sync path pointing to the above path

**Pull request merged**
