### PR TITLE
Fix folder scheduled twice

### PR DESCRIPTION
**Pull request by TheOneRing**
The code was a broken duplication of:
https://github.com/owncloud/client/blob/f31e61dc475f2ced235a5064667ee49bb9572cb6/src/gui/folder.cpp#L1091-L1112

Erroneously implemented in https://github.com/owncloud/client/commit/99f71b3dfb3c58a575e0bdb8d375aa311d27cffb at the time I assumed it was by accident removed during the rewrite.

Please compare both implementation, all I can say the current state doesn't make sense.

---

So it looks like that before the refactoring we already had the duplication in the folderman and the folder...

### CODE REVIEW

**Review by erikjv — APPROVED** [review]

**Comment by TheOneRing** [comment]
Blocked: Needs discussion
The file is only added to the ignore list after ~3 failed tries.
We have to retry it at least one time more if we want to make sure to sync the other files.

**Comment by erikjv** [comment]
I think it looks ok. Do you want to discuss anything?

**Comment by TheOneRing** [comment]
> I think it looks ok. Do you want to discuss anything?

I hid the outdated comment asking for discussion, this is 100% ready for review.

**Comment by saw-jan** [comment]
I see crash related to `SyncScheduler`:
builds: https://drone.owncloud.com/owncloud/client/17576/5/15
```c
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fc37340a844 in __pthread_kill_implementation () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7fc36fd2ef00 (LWP 2580))]
#0  0x00007fc37340a844 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007fc3733b9abe in raise () at /lib64/libc.so.6
#2  0x00007fc3733a290f in abort () at /lib64/libc.so.6
#3  0x00007fc3739860eb in qgetenv(char const*) [clone .cold] () at /lib64/libQt6Core.so.6
#4  0x00007fc373986b7f in  () at /lib64/libQt6Core.so.6
#5  0x00007fc373986083 in qt_assert_x(char const*, char const*, char const*, int) () at /lib64/libQt6Core.so.6
#6  0x00000000005f9603 in OCC::SyncScheduler::enqueueFolder(OCC::Folder*, OCC::SyncScheduler::Priority) (this=0x1ec5550, folder=0x1e42c70, priority=OCC::SyncScheduler::Priority::Low) at /drone/src/src/gui/scheduling/syncscheduler.cpp:137
#7  0x00000000004e4222 in OCC::Folder::slotSyncFinished(bool)::$_1::operator()() const (this=0x2a9b910) at /drone/src/src/gui/folder.cpp:1111
#8  0x00000000004e41b6 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, OCC::Folder::slotSyncFinished(bool)::$_1>::call(OCC::Folder::slotSyncFinished(bool)::$_1&, void**) (f=..., arg=0x7ffc4d6d96e0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:127
#9  0x00000000004e4181 in QtPrivate::Functor<OCC::Folder::slotSyncFinished(bool)::$_1, 0>::call<QtPrivate::List<>, void>(OCC::Folder::slotSyncFinished(bool)::$_1&, void*, void**) (f=..., arg=0x7ffc4d6d96e0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:241
#10 0x00000000004e4121 in QtPrivate::QFunctorSlotObject<OCC::Folder::slotSyncFinished(bool)::$_1, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x2a9b900, r=0x1e42c70, a=0x7ffc4d6d96e0, ret=0x0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:408
#11 0x00007fc373a9b80a in QSingleShotTimer::timerEvent(QTimerEvent*) () at /lib64/libQt6Core.so.6
#12 0x00007fc373a7c6df in QObject::event(QEvent*) () at /lib64/libQt6Core.so.6
#13 0x00007fc374d70698 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt6Widgets.so.6
#14 0x00007fc373a29018 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt6Core.so.6
#15 0x00007fc373bd6763 in QTimerInfoList::activateTimers() () at /lib64/libQt6Core.so.6
#16 0x00007fc373cf9159 in timerSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt6Core.so.6
#17 0x00007fc372f9248c in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#18 0x00007fc372ff0648 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#19 0x00007fc372f8fb13 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#20 0x00007fc373cf945f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt6Core.so.6
#21 0x00007fc373a3612b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt6Core.so.6
#22 0x00007fc373a318fd in QCoreApplication::exec() () at /lib64/libQt6Core.so.6
#23 0x0000000000450920 in main(int, char**) (argc=6, argv=0x7ffc4d6da298) at /drone/src/src/gui/main.cpp:543
        resource = {<No data fields>}
        platform = std::unique_ptr<OCC::Platform> = {get() = 0x1da0b00}
        app = <incomplete type>
        displayLanguage = {d = {d = 0x1e0b490, ptr = 0x1e0b4a0 u"en_US", size = 5}, static _empty = 0 u'\000'}
        options = {show = true, quitInstance = false, logDir = {d = {d = 0x0, ptr = 0x0, size = 0}, static _empty = 0 u'\000'}, logFile = {d = {d = 0x1ec2180, ptr = 0x1ec2190 u"-", size = 1}, static _empty = 0 u'\000'}, logFlush = true, logDebug = true, debugMode = false, fileToOpen = {d = {d = 0x0, ptr = 0x0, size = 0}, static _empty = 0 u'\000'}}
        singleApplication = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fc373eed460 <QObject::staticMetaObject>}, stringdata = 0x7fc37599c240 <(anonymous namespace)::qt_meta_stringdata_KDSingleApplication>, data = 0x7fc37599c160 <qt_meta_data_KDSingleApplication>, static_metacall = 0x7fc375997cc0 <KDSingleApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, metaTypes = 0x7fc37599eb20 <qt_incomplete_metaTypeArray<(anonymous namespace)::qt_meta_stringdata_KDSingleApplication_t, QtPrivate::TypeAndForceComplete<QString, std::integral_constant<bool, true> >, QtPrivate::TypeAndForceComplete<bool, std::integral_constant<bool, true> >, QtPrivate::TypeAndForceComplete<KDSingleApplication, std::integral_constant<bool, true> >, QtPrivate::TypeAndForceComplete<void, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<QByteArray const&, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<bool, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<QByteArray const&, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<bool, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<QByteArray const&, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<int, std::integral_constant<bool, false> > >>, extradata = 0x0}}, d_ptr = std::unique_ptr<KDSingleApplicationPrivate> = {get() = 0x1ec2290}}
        folderManager = std::unique_ptr<OCC::FolderMan> = {get() = 0x1ec46c0}
        ocApp = std::unique_ptr<OCC::Application> = {get() = 0x1e30420}

```

**Comment by fmoc** [comment]
Please open a new issue so that we can have a look.

**Comment by saw-jan** [comment]
New issue reported (https://github.com/owncloud/client/issues/11495)

**Pull request merged**
