### PR TITLE
Mac: Display docker icon when settings are visible

### PR DESCRIPTION
**Pull request by TheOneRing**

### CODE REVIEW

**Comment by guruz** [comment]
Nice!
I wanted to do this for a long time, but never did it :-)
Only downside I see is that people might not understand that there is a menu bar icon. (they probably didnt understand before either..)
I solved this in ocsmount by force-showing the menu after the configuration dialog is closed.

**Comment by jnweiger** [comment]
Crude screenshots:
First with the settings window open, second with the settings window closed:





In both cases, we have a small icon in the top icon bar, and a large owncloud icon in the bottom dock panel.

**Comment by jnweiger** [comment]
@TheOneRing @michaelstingl should the big owncloud icon in the dock disappear, when we close the settings window? On Linux it disappears.

**Comment by TheOneRing** [comment]
It will disappear, but the dock displays the last few used applications when not more than n windows are open.

**Comment by jnweiger** [comment]
That is more userfriendly than expected. OK.

**Pull request merged**
