### PR TITLE
Delta sync

### PR DESCRIPTION
**Pull request by ogoffart**

### CODE REVIEW

**Comment by ogoffart** [comment]
The TestChunkingNG::testResume3 test is failling.

```
[ info sync.propagator.upload ]:      Resuming  "A/a0" ; sent = 11000000 ; total= 30000000
```

While normally everything was supposed to be sent.

**Comment by ogoffart** [comment]
Test passes now passes on linux.

Windows error:

```
CMake Error at src/libsync/CMakeLists.txt:127 (add_library):
Cannot find source file:
 ../3rdparty/zsync/c/librcksum/hash.c
```

**Comment by ogoffart** [comment]
@domme: I guess the zsync submodule is not checked out...  can you have a look?

**Comment by dschmidt** [comment]
Sorry, domme that highlight was for me - nice nickname tho! :-)

The windows build error is a bit spurious, we define that we want submodules to be checked out in our Craft blueprint:
https://github.com/owncloud/craft-blueprints-owncloud/blob/master/owncloud/owncloud-client/owncloud-client.py#L33

@TheOneRing Is something broken in GitSource in Craft maybe?

**Comment by ogoffart** [comment]
The new error on Windows is:

```
C:\projects\client\src\3rdparty\zsync\c\libzsync/zsync.h(35): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
6406C:\projects\client\src\3rdparty\zsync\c\libzsync/zsync.h(35): error C2146: syntax error: missing ';' before identifier 'zsync_file_length'
6407C:\projects\client\src\3rdparty\zsync\c\libzsync/zsync.h(77): error C2143: syntax error: missing ';' before '*'
6408C:\projects\client\src\3rdparty\zsync\c\libzsync/zsync.h(77): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
6409C:\projects\client\src\3rdparty\zsync\c\libzsync/zsync.h(77): error C2086: 'int off_t': redefinition
6410C:\projects\client\src\3rdparty\zsync\c\libzsync/zsync.h(35): note: see declaration of 'off_t'
6411C:\projects\client\src\3rdparty\zsync\c\libzsync/zsync.h(102): error C2061: syntax error: identifier 'off_t'
6412C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\sys/types.h(42): error C2378: 'off_t': redefinition; symbol cannot be overloaded with a typedef
6413C:\projects\client\src\3rdparty\zsync\c\libzsync/zsync.h(35): note: see declaration of 'off_t'
6414c:\projects\client\src\3rdparty\zsync\c\libzsync\sha1.h(44): error C2061: syntax error: identifier 'off_t'
6415C:\projects\client\src\3rdparty\zsync\c\libzsync/zsyncfile.h(27): error C3646: 'len': unknown override specifier
6416C:\projects\client\src\3rdparty\zsync\c\libzsync/zsyncfile.h(27): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
6417C:\projects\client\src\3rdparty\zsync\c\libzsync/zsyncfile.h(63): error C2146: syntax error: missing ')' before identifier 'len'
6418C:\projects\client\src\libsync\propagatecommonzsync.cpp(90): error C3861: 'dup': identifier not found
6419C:\projects\client\src\libsync\propagatecommonzsync.cpp(90): error C2664: 'std::unique_ptr<FILE,std::function<void (FILE *)>>::unique_ptr(const std::unique_ptr<FILE,std::function<void (FILE *)>> &)': cannot convert argument 1 from 'OCC::ZsyncSeedRunnable::run::<lambda_83710fd4193c43aebd9dbec9814a3f48>' to 'std::nullptr_t'
6420C:\projects\client\src\libsync\propagatecommonzsync.cpp(92): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
6421C:\projects\client\src\libsync\propagatecommonzsync.cpp(149): error C3861: 'dup': identifier not found
6422C:\projects\client\src\libsync\propagatecommonzsync.cpp(149): error C2664: 'std::unique_ptr<FILE,std::function<void (FILE *)>>::unique_ptr(const std::unique_ptr<FILE,std::function<void (FILE *)>> &)': cannot convert argument 1 from 'OCC::ZsyncSeedRunnable::run::<lambda_fe9dc769097f4697a90080f31f1ae807>' to 'std::nullptr_t'
6423C:\projects\client\src\libsync\propagatecommonzsync.cpp(151): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
6424C:\projects\client\src\libsync\propagatecommonzsync.cpp(160): warning C4138: '*/' found outside of comment
6425C:\projects\client\src\libsync\propagatecommonzsync.cpp(162): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
6426C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\string.h(182): note: see declaration of 'strerror'
6427C:\projects\client\src\libsync\propagatecommonzsync.cpp(173): error C3861: 'dup': identifier not found
6428C:\projects\client\src\libsync\propagatecommonzsync.cpp(173): error C2664: 'std::unique_ptr<FILE,std::function<void (FILE *)>>::unique_ptr(const std::unique_ptr<FILE,std::function<void (FILE *)>> &)': cannot convert argument 1 from 'OCC::ZsyncGenerateRunnable::run::<lambda_db2a2b1842b63efa8306b7b701e8a94d>' to 'std::nullptr_t'
6429C:\projects\client\src\libsync\propagatecommonzsync.cpp(175): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
6430C:\projects\client\src\libsync\propagatecommonzsync.cpp(179): error C3861: 'dup': identifier not found
6431C:\projects\client\src\libsync\propagatecommonzsync.cpp(179): error C2664: 'std::unique_ptr<FILE,std::function<void (FILE *)>>::unique_ptr(const std::unique_ptr<FILE,std::function<void (FILE *)>> &)': cannot convert argument 1 from 'OCC::ZsyncGenerateRunnable::run::<lambda_915f56b107f475c65ddb19a7cb1e5763>' to 'std::nullptr_t'
6432C:\projects\client\src\libsync\propagatecommonzsync.cpp(181): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
6433C:\projects\client\src\libsync\propagatecommonzsync.cpp(198): error C3861: 'dup': identifier not found
6434C:\projects\client\src\libsync\propagatecommonzsync.cpp(198): error C2664: 'std::unique_ptr<FILE,std::function<void (FILE *)>>::unique_ptr(const std::unique_ptr<FILE,std::function<void (FILE *)>> &)': cannot convert argument 1 from 'OCC::ZsyncGenerateRunnable::run::<lambda_9c9170df2d5bc1c2ee7e977c0f31e500>' to 'std::nullptr_t'
6435C:\projects\client\src\libsync\propagatecommonzsync.cpp(200): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

**Comment by ogoffart** [comment]
Now it builds, but still some test failures on windows:


```
09-20 09:32:56:526 [ info sync.networkjob ]:	OCC::SimpleNetworkJob created for "http://localhost/owncloud" + "" "OCC::Account"
09-20 09:32:56:526 [ info sync.networkjob.zsync.get ]:	Retrieved zsync metadata for: "A/a0" size: 2432 etag: "165f65342ec"
unlink: Permission denied
09-20 09:32:56:592 [ critical sync.networkjob.zsync.get ]:	"Unable to rename temporary file."
09-20 09:32:56:592 [ info sync.networkjob ]:	OCC::DeleteJob created for "http://localhost/owncloud" + "" "OCC::GETFileZsyncJob"
09-20 09:32:56:592 [ warning sync.propagator ]:	Could not complete propagation of "A/a0" by OCC::PropagateDownloadFile(0x128d468) with status 2 and error: "Unable to rename temporary file."
09-20 09:32:56:592 [ info sync.networkjob.delete ]:	DELETE of QUrl("http://admin@localhost/owncloud/remote.php/dav/files/admin/A/a0?zsync") FINISHED WITH STATUS "OK"
09-20 09:32:56:593 [ info sync.database ]:	Closing DB "C:/Users/appveyor/AppData/Local/Temp/1/ZsyncTest-VEzbOJ/._sync_test.db"
09-20 09:32:56:673 [ info sync.engine ]:	CSync run took  243 ms
FAIL!  : TestZsync::testFileDownloadSimple() 'fakeFolder.syncOnce()' returned FALSE. ()
C:\projects\client\test\testzsync.cpp(123) : failure location
```

**Comment by ogoffart** [comment]
@ckamm,  CI is passing now, can you have a look again at the changes?

**Pull request merged**
