### PR TITLE
Fix translated icon names in desktop file

### PR DESCRIPTION
**Pull request by fmoc**
Follow-up for #9150, which fixed the generic icon but not the translated ones. Those translated `Icon` entries were completely redundant, so simply removing it fixes the issue and removes some bloat.

The second commit fixes an (accidentally?) translated placeholder for the `el` locale.

### CODE REVIEW

**Comment by TheOneRing** [comment]
Please target 2.10

**Comment by dschmidt** [comment]
Is this file exclusively manually edited? Then this seems to be fine

**Review by dschmidt — APPROVED** [review]

**Review by TheOneRing — CHANGES_REQUESTED** [review]
Please target 2.10

**Comment by TheOneRing** [comment]
> Is this file exclusively manually edited? Then this seems to be fine

We used to have automatic translations from transifex for that file,  until they stopped the support without notice.

**Review by TheOneRing — APPROVED** [review]

**Pull request merged**
