### PR TITLE
Fix Debian 7 builds

### PR DESCRIPTION
**Pull request by dschmidt**

### CODE REVIEW

**Comment by guruz** [comment]
👍 with me.
Is this only broken on master or also 2.2.x?

**Comment by guruz** [comment]
(I guess so because of https://github.com/owncloud/client/pull/5759/files ?)

**Comment by dschmidt** [comment]
Exactly - so it only affects 2.3.2

**Comment by guruz** [comment]
@dschmidt Sorry I meant 2.3.x.. then your PR should go to 2.3 branch

**Comment by dschmidt** [comment]
That didnt quiten work because of the merges. Will reopen later

**Pull request closed without merging**
