### PR TITLE
Fix documentation build process

### PR DESCRIPTION
**Pull request by settermjd**
This PR:

- Fixes the documentation build process so that it can run in a UNIX/Linux environment. 

:information_desk_person: I see that `doc/Makefile` was removed in 98efab83, but I'm not sure why. May need further investigation to fully appreciate the reasons for the decision, at the time.

### CODE REVIEW

**Comment by guruz** [comment]
Might as well be an accidental removal by @dragotin ?

**Comment by settermjd** [comment]
Could well be. After some investigation, the "Generic Build Instructions" are not complete and definitely need some updates. For example, that Ubuntu 14.04 is not supported, as documented in https://github.com/owncloud/client/issues/4617, needs to be mentioned.

**Comment by settermjd** [comment]
I'm going to merge this one to get the build working again, as it's a sufficiently high priority. Then I'm going to update the docs. In the process of doing so, this PR may become unecessary. But, at least we're moving forward.

**Comment by guruz** [comment]
👍

**Pull request merged**
