### PR TITLE
Update windows docker file to use 2.3 OBS repo

### PR DESCRIPTION
**Pull request by rullzer**
While building a themed client for 2.3 I noticed your Dockerfile was not up to date.

### CODE REVIEW

**Comment by guruz** [comment]
Thanks. I don't think we're using that file anymore.

**Comment by ogoffart** [comment]
@guruz,  if we don't use it, we need to remove it.  Also the documentation still mention it.

**Comment by rullzer** [comment]
@guruz as @ogoffart mentions it is still in the docs :)

**Comment by ogoffart** [comment]
Even if we use another script on obs, the docker image still need to be kept up to date.

**Pull request merged**
