### PR TITLE
Overlay icon fixes

### PR DESCRIPTION
**Pull request by jturcotte**

### CODE REVIEW

**Comment by jturcotte** [comment]
fd157cdd3471131412327b5ff64204b77b545d92 is not absolutely necessary. It simplifies the implementation but doesn't fix any issue.

**Comment by dragotin** [comment]
cool, but before we merge this, can you please review and fix https://github.com/owncloud/client/wiki/Overlay-Icons ? Thanks @jturcotte

**Comment by jturcotte** [comment]
@dragotin Updated with the current protocol. I didn't cover the sharing part though as I don't know it well.

**Comment by dragotin** [comment]
:+1: @jturcotte please merge

**Comment by jturcotte** [comment]
Manually merged into 2.2 as a branch instead of a squash commit in master.

**Pull request merged**
