### PR TITLE
The share-permissions namespace was moved

### PR DESCRIPTION
**Pull request by rullzer**
See https://github.com/owncloud/core/pull/24017

This was done since other services we want to intergrate with don't use
the ownCloud namespace.

Once https://github.com/owncloud/core/pull/24017 is in. Pleae give it a quick test.

### CODE REVIEW

**Comment by guruz** [comment]
That's unreleased code right? So we don't need any special stuff for old/new namespace?

**Comment by guruz** [comment]
If yes then: :+1:

**Comment by rullzer** [comment]
yes unreleased :)

**Comment by guruz** [comment]
:+1: 
(didnt test it..)

**Comment by rullzer** [comment]
Merged in master.
Quick test worked for me so merging.

**Pull request merged**
