### PR TITLE
Fix a string line 984

### PR DESCRIPTION
**Pull request by seal20**
Added a missing in to "Not allowed because you don't have permission to add subfolders *in* that folder"

### CODE REVIEW

**Comment by dragotin** [comment]
Not rather "...to add subfolders **to** that folder" ?

**Comment by dragotin** [comment]
@danimo your turn

**Comment by seal20** [comment]
sorry not native... just wanted to point the typo.

**Comment by danimo** [comment]
Superseeded by f1a9e669b45ea1dc8fef91a93efd0b6c313957dd. Thanks!

**Pull request closed without merging**
