### PR TITLE
Use Qt 5.10 on Windows

### PR DESCRIPTION
**Pull request by dschmidt**
... and fix AppVeyor Build.

### CODE REVIEW

**Comment by guruz** [comment]
FYI Qt 5.10.1 is supposed to come out "Januar 2018"...

**Comment by dschmidt** [comment]
retest this please

**Comment by guruz** [comment]
5.10.1 is released

**Comment by ogoffart** [comment]
So can this be merged?

**Comment by dschmidt** [comment]
Yes, totally!

**Comment by ogoffart** [comment]
Merging, then.

**Pull request merged**
