### PR TITLE
FolderWatcher: Act on relative paths #5116

### PR DESCRIPTION
**Pull request by guruz**

### CODE REVIEW

**Comment by dragotin** [comment]
Can you explain why this patch helps? Thx.

**Comment by guruz** [comment]
See @ckamm 's comments in the original issue.
Basically if the sync directory or the directory containing the sync directory is a symlink, the folder watcher fired events for that link target)
E.g. on OS X /tmp is actually /private/tmp so if you have a sync directory in /tmp you'd get the watcher events for /private/tmp which will then be ignored by the sync client

**Comment by guruz** [comment]
@ckamm Tested, please review and squash-merge and add to https://github.com/owncloud/client/issues/5168

**Comment by ckamm** [comment]
:+1:

**Pull request merged**
