### PR TITLE
Propagator: Also upload more in parallel

### PR DESCRIPTION
**Pull request by guruz**
Fix for https://github.com/owncloud/client/issues/4986#issuecomment-227071801

This is before we have bundling at some point.

### CODE REVIEW

**Comment by ckamm** [comment]
@ogoffart Was there a reason uploads were never marked as likely to finish quickly?

**Comment by guruz** [comment]
@ogoffart If there was one (I don't remember for sure) it was: "let's try first if this does not mess up the server load too much"

**Comment by ogoffart** [comment]
Why the magic value of 10KiB ?  Where does that number comes from?

**Comment by guruz** [comment]
@ogoffart it's 100 not 10.
I took less than for the download magic value because I'm assuming a PUT is more costly time wise on the server

**Comment by ogoffart** [comment]
Yeah, i just wonder why this value and not 200 or 50 ?
Did you just select randomly?

**Pull request merged**
