### PR TITLE
Fix linking with libinotify on OpenBSD.

### PR DESCRIPTION
**Pull request by yason**
Builds fine on NetBSD, builds and runs on FreeBSD.

### CODE REVIEW

**Comment by guruz** [comment]
@ogoffart Can you check if this breaks the linux build?

**Comment by guruz** [comment]
@yason Thanks a lot, can you fill https://owncloud.org/contribute/agreement/ ?

**Comment by yason** [comment]
I have already sent this form to Frank. BTW, this is not referenced to an issue I've opened some time ago. I'm still looking for solution.

**Comment by ogoffart** [comment]
:+1:  compiled on linux and looks good to me

**Comment by ogoffart** [comment]
This is now merged in 2.0

**Pull request closed without merging**
