### PR TITLE
fix python3 syntax errors

### PR DESCRIPTION
**Pull request by hefee**
The print statement needs brackets.

### CODE REVIEW

**Comment by ogoffart** [comment]
And does it still work with python2?

**Comment by danimo** [comment]
Yes, you can add any amount of braces in python.

**Comment by hefee** [comment]
@ogoffart "And does it still work with python2?"
If it compiles under python2 is complety uninteressting. The File header says 
  #!/usr/bin/python3

=> it is a python3 script.

**Comment by dragotin** [comment]
hmm, do we really have to force it to python 3? There might still be systems out that default to python 2 and we do not pull python3 for them, right?

**Pull request merged**
