### PR TITLE
Adding new resource for the desktop.ini file

### PR DESCRIPTION
**Pull request by DeepDiver1975**
The new project on transifex - https://www.transifex.com/owncloud-org/owncloud/client-desktop/

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Here we go

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/client/commit/8694db1c4995d12c15cf8a33455dfc7511e890c4#diff-5432296e16dadebb5595f3ec652209ee

**Comment by danimo** [comment]
Thanks!

**Comment by DeepDiver1975** [comment]
NP - what about the shell extensions? Any strings to be translated as well?

**Comment by guruz** [comment]
@DeepDiver1975 AFAIK no, we transmit the strings via socket from client to shell extension.

**Pull request merged**
