### PR TITLE
Replace custome date parser QDateTime::fromString(value, Qt::RFC2822D…

### PR DESCRIPTION
**Pull request by TheOneRing**
…ate)

Should we wait until after 2.7.0?

### CODE REVIEW

**Comment by dschmidt** [comment]
Let's wait

**Comment by jnweiger** [comment]
Do you have an example, what is fixed by this?

**Comment by TheOneRing** [comment]
It replaces a whole lot of unmaintained custom copy paste code with a Qt function.
It introduces, error detection on the level of the log.
Its supposed to properly handle other time zones while the old code only assumed gmt.

**Comment by TheOneRing** [comment]
Targeting master now

**Review by dschmidt — APPROVED** [review]

**Pull request merged**
