### PR TITLE
Add option to disable the delete all files prompt

### PR DESCRIPTION
**Pull request by Bottswana**
Hello Folks,
I added this feature for my own purposes and thought I'd create a PR in case you wanted to merge it, given you have this as a request pending: https://github.com/owncloud/client/issues/1408

This PR adds an option to the generic settings page, default enabled, to control the display of the all files deletion prompt.

I'm not sure if this patch is considered trivial or not, so if you need me to sign the contributor agreement I can do that.

### CODE REVIEW

**Comment by guruz** [comment]
Hi, in General: Yes, we'd Need you to sign the contributor Agreement :)

If the patch will be taken or not is not decided, in General adding Options in UI is always a bit discouraged.

FYI @jancborchardt

**Comment by Bottswana** [comment]
That's no issue, I'll wait until that is decided before signing the agreement though to save workload.
If there's an alternative suggestion other than providing an option in the GUI, I'm happy to implement, but based on the linked issue, the removal of the dialog seemed 50/50, so it made sense to provide the choice to the end user.

Thanks!

**Comment by jancborchardt** [comment]
What’s the use-case of this setting?

**Comment by Bottswana** [comment]
So our use case for this in this scenario is we create users with no files in and the client running on a machine, and then share folders or files to the user when they need access to them. In this scenario, when a sync occurs that would remove all files (Which we do at the end of each day), nothing is removed and the prompt appears requiring user intervention.

In our use case, we need to have full control of what the client is doing, and not prompt the user if the action should take place. 

For my home use of ownCloud, I like this prompt and would not like it removed, but in the use case I stated above, its presence breaks the entire model we are creating.

I'm happy with just merging this in for our clients when we use it in this case, but you had an open issue for it, so I presume other people would want this option too.

Thanks

**Comment by dragotin** [comment]
I would not like to have that exposed in the GUI, but it could be an option that can be set in the config file by the admin, and also later be set through server based options.

**Comment by Bottswana** [comment]
I can easily remove the option from the GUI and leave it as config file option only, but that does seem a little cryptic for something which is only affecting the GUI itself in my opinion.

**Comment by jancborchardt** [comment]
Yeah, totally agree with @dragotin here. This setting would deactivate a pretty useful and crucial feature. Also, it seems useful only for very few use-cases compared to the other settings, so adding it in the GUI isn’t really justified.

**Comment by Bottswana** [comment]
Are we happy then to drop the GUI option and leave it as a config level
option for use cases such as mine?

**Comment by guruz** [comment]
@Bottswana Yes please change the PR :)
And submit the contributor agreement.
Thanks for contributing!

**Comment by Bottswana** [comment]
Thanks,
PR Updated and agreement signed and emailed.

**Comment by karlitschek** [comment]
confirmed that I got the agreement :-)

**Comment by ogoffart** [comment]
Thanks for the pull request:

Regarding the code: please do not add a dependency between the sync engine and the config file.  
Please put the logic in Folder::slotAboutToRemoveAllFiles.

Regarding the UI, maybe a "don't show again" checkbox would be acceptable

**Comment by Bottswana** [comment]
No worries, Will do this after I get back from cisco live.
In regards to the UI, if you wish me to implement that box, thats no worries. But if it is still preferred to be config only, I dont want to waste any time.
-J

**Comment by ogoffart** [comment]
i don't know what @jancborchardt  will think about this checkbox.  Personally i believe it's a good thing to have.  But this can be done in another pull request regardless

**Comment by wmarkus85** [comment]
HI my config look like:
[General]
optionalDesktopNotifications=true
crashReporter=false
monoIcons=false
newBigFolderSizeLimit=500
useNewBigFolderSizeLimit=false
promptDeleteFiles=false

[Accounts]

Client Version  2.2.0-nightly20160215 (build 5851)

but the pop up still appears. -> what's wrong?
BR Markus

**Comment by Bottswana** [comment]
This isn't merged yet, are you using the copy from my fork?

**Comment by wmarkus85** [comment]
which copy?

**Comment by jancborchardt** [comment]
@ogoffart as said above I agree with @dragotin 

> I would not like to have that exposed in the GUI, but it could be an option that can be set in the config file by the admin, and also later be set through server based options.

**Comment by ogoffart** [comment]
@jancborchardt the original patch added an option in the settings UI.  Here I was talking about a "[x] do not show again"  checkbox on the message box itself.

**Comment by jancborchardt** [comment]
Doesn’t fully make sense in this case because it’s a valid warning every time it appears. And it appears every time for a reason. As people are prone to click »ok« on these warnings and check everything that looks like a »don’t show again«, it wouldn’t be proper to offer that here.

**Comment by guruz** [comment]
I merged it prematuerely... thanks @ogoffart for fixing the things mentioned in https://github.com/owncloud/client/pull/4389#issuecomment-181418098 .. :+1:

**Comment by RealRancor** [comment]
Please don't forget to add this option to the documentation of the available config files at:

https://doc.owncloud.org/desktop/2.2/advancedusage.html#configuration-file

**Comment by guruz** [comment]
done..

**Comment by JarbyDev** [comment]
Hello everytime a file got deleted in web UI, i got this warning in the desktop, how i can  disabled this, Thanks

nc

**Comment by RealRancor** [comment]
@JarbyDev As you're running the nextcloud client (and probably also nextcloud itself) most likely the sames an in https://github.com/owncloud/client/issues/5265#issuecomment-255511121 applies here.

**Comment by JarbyDev** [comment]
I have 2 instances one owncloud and one nextcloud, (i get the same pop up in both instances) also i tried to go to the configuration file but i dont see the option promptDeleteAllFiles.

This is my current owncloud,cfg

[General]
optionalDesktopNotifications=true

[Accounts]
0\Folders\1\localPath=C:/Users/jarbydev/JMH Drive/
version=2
0\Folders\1\targetPath=/
0\url=https://owncloud.example.com
0\Folders\1\paused=false
0\serverVersion=
0\Folders\1\ignoreHiddenFiles=true
0\http_certificatePasswd=
0\http_certificatePath=
0\http_user=jarbydev
0\authType=http
0\user=jagudelo

**Comment by RealRancor** [comment]
@JarbyDev You're really in the wrong place here (in this Pull Request). If you think there is an issue here create a new bugreport...

**Comment by RealRancor** [comment]
To sum-up:

- This is a bugtracker. Questions like this should always go to https://central.owncloud.org/
- A Pull Request shouldn't be misused to ask questions about a feature. If there is a issue with a new introduced feature like this a new issue should be created
- If you have issues with the nextcloud client against a ownCloud server and a Nextcloud server issues with that client needs to go to https://github.com/nextcloud/client_theming
- If you think the issue is caused by the server a new issue should go to the specific server issue tracker (oC or NC)

**Comment by Bottswana** [comment]
Just add the line to your config file under general and restart the client.
Its a 'hidden' config option.

promptDeleteAllFiles=false

**Pull request merged**
