### PR TITLE
fix win install instructions: build path and docker image name

### PR DESCRIPTION
**Pull request by butonic**
1. admin/win32 -> admin/win
2. the owncloud-client-win32 image needs to be all lowercase

### CODE REVIEW

**Comment by carlaschroder** [comment]
:+1:  for spelling and grammar. Thanks @butonic

**Comment by danimo** [comment]
Patch is correct but wrong branch. Master is dead at the moment. Please create a PR against 2.2. Thanks!

**Comment by butonic** [comment]
@carlaschroder can you take care of that? pretty please?

**Comment by carlaschroder** [comment]
Yes @butonic. You owe me a slice of pizza :)

**Comment by butonic** [comment]
:pizza:

**Pull request closed without merging**
