### PR TITLE
Merge 2.6 in master

### PR DESCRIPTION
**Pull request by ogoffart**

### CODE REVIEW

**Comment by TheOneRing** [comment]
@micbar how can we handle the seperate change logs?
can we only merge once we have prepared the 2.6.2 change log folder?

**Comment by TheOneRing** [comment]
Bevore we merge it we need to rename the unreleased folder on 2.6 to "2.6.2".
Else the 2.7 and the 2.6 changes will get mixed up

**Comment by ogoffart** [comment]
But the changelog generatin is failing: 

> + calens >| CHANGELOG.md
> file changelog/unreleased/7247: title is too long

I guess this should be fixed in the 2.6 branch

**Comment by ogoffart** [comment]
It looks like appvoyar is failling because it cannot fetch some ressources from the network. 
So i'll just merge this

**Pull request merged**
