### PR TITLE
Make sure all elements in row have same height

### LINKED ISSUE #11094: Unify button/widget height in advanced configuration page
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The "reset to default" button introduced in https://github.com/owncloud/client/pull/11092 appears taller than the button next to it.

### Expected behavior

The UI elements in this line should have the same height.

### Steps to reproduce the issue

_No response_

### Screenshots

_No response_

### Logs

_No response_

### Client version number

5.0.0 master (post https://github.com/owncloud/client/pull/11092).

### Desktop environment (Linux only)

_No response_

### Client package version and origin (Linux only)

_No response_

### Installation path (Windows only)

_No response_

### Server information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fmoc**
Fixes #11094.

screenshot_2023-08-17_12-39-47

### CODE REVIEW

**Comment by TheOneRing** [comment]
Hmm have you tried just using the same class for both buttons?

**Comment by fmoc** [comment]
I did. The icon just increases the height anyway.

**Comment by TheOneRing** [comment]
@erikjv what do you think? for me it feels a bit wrong that we need to enforce the size.
@fmoc please fix the ui file.

**Comment by fmoc** [comment]
I'll do, and I'll try to make the buttons expand vertically automatically.

**Review by TheOneRing — APPROVED** [review]

**Pull request merged**
