### PR TITLE
Abort the request and reset the QNAM if user does not ACK a new cert.

### PR DESCRIPTION
**Pull request by dragotin**
This is supposed to fix bug #3283

### CODE REVIEW

**Comment by dragotin** [comment]
@guruz asked me to verify again if the QNAM reset is really needed. It is. If it is not there, at the next sync the client proceeds without popping up the window again. That happens probably because of the if routine here: https://github.com/owncloud/client/blob/master/src/libsync/account.cpp#L497 which just returns in case of having ```_treatSslErrorsAsFailure``` set to true.

I fail to understand why the cert is accepted in that case and QNAM continues to handle the requests.

Because of that,  my suggestion is to keep the QNAM reset for 1.8.2 which fixes the initial problem. Later on, we should refactor the AbstractNetworkJob to care for the _treatSslErrorsAsFailure properly.

**Comment by LukasReschke** [comment]
Patch confirmed :+1:

@jklmnn You are welcome to test this patch as well. We have built a nightly available from https://software.opensuse.org/download/package?project=isv:ownCloud:community:nightly&package=owncloud-client that includes the patch. If you do this please change back to the regular ownCloud client packages afterwards as we don't recommend using that nightly repository :smile:

**Comment by jklmnn** [comment]
@LukasReschke thanks for that info, I'll test it as soon as I will have time.

**Comment by ogoffart** [comment]
It would be good to understand why this works. 
Or rather why it breaks now,  we should not call ignoreSslErrors if the dialog is not accepted.  Do we do that? Then that's the problem.  We don't?  Then why are the request continuing?

**Comment by dragotin** [comment]
@ogoffart no, we do not call ignoreSslErrors if the dialog is not accepted.

**Comment by ckamm** [comment]
@dragotin I also confirm that the patch fixes the issue.

**Comment by dragotin** [comment]
Ok. I'll merge to 1.8 branch and create an issue that this need further investigation.

**Pull request merged**
