### PR TITLE
SyncEngine: Keep local size in SyncItem #5855

### PR DESCRIPTION
**Pull request by guruz**

### CODE REVIEW

**Comment by ckamm** [comment]
Looks good to me

**Comment by guruz** [comment]
Thanks. Still waiting for @mrow4a for smashbox :)

**Comment by guruz** [comment]
TestSyncFileStatusTracker fails in CI but not here hmm

**Comment by guruz** [comment]
TODO after this is merged: uncomment test in https://github.com/owncloud/client/pull/5868

**Comment by guruz** [comment]
```
FAIL!  : TestChunkingNG::testResumeServerDeletedChunks() Compared values are not the same
   Actual   (fakeFolder.currentRemoteState().find("A/a0")->size): 259258112
   Expected (size)                                              : 300000000
   Loc: [/var/lib/jenkins/workspace/cloud-client_client_PR-5871-MXDTTGRVL25TEMF7D2LYYV5TXHZOS5OYZSKQPXS5EBWEF52I3VSQ/test/testchunkingng.cpp(233)]
```
works for me locally though

**Comment by mrow4a** [comment]
Smashbox says ok :+1:

**Pull request merged**
