### PR TITLE
[2.5] Drop Jenkinsfile, replaced by DroneCI

### PR DESCRIPTION
**Pull request by tboerger**
So far DroneCI is showing stable results, that's the point in time where
we can get rid of Jenkins :bomb:

### CODE REVIEW

**Comment by ogoffart** [comment]
But now, of course, Jenkins is failling. as it cannot find the jenkinsfile.

Maybe removing the jenkinsfile is not the right way to disable jenkins. There is maybe some option we need to toggle in github or in jenkins.

**Comment by patrickjahns** [comment]
@ogoffart 
Can do - but then its for all branches - just let me know if thats okay

**Comment by guruz** [comment]
@patrickjahns Yes please remove, if drone runs the same tests.

**Comment by tboerger** [comment]
If everything is fine with this pr we have to disable the client pipeline within jenkins and we have to verify that the webhook from the repo have been dropped.

**Comment by guruz** [comment]
> All checks have passed
4 successful checks

**Pull request merged**
