### PR TITLE
Use zsyncfile API, remove duplicated code

### PR DESCRIPTION
**Pull request by ckamm**
Combines with https://github.com/ahmedammar/zsync/pull/1

Note that this is based on https://github.com/owncloud/client/pull/6382 to allow actual testing. This PR has only one commit: https://github.com/owncloud/client/commit/c742b4a9ec35414d360e81651c1e5698dfed96d4

### CODE REVIEW

**Comment by ogoffart** [comment]
CI system is confused:

```
fatal: reference is not a tree: dde7f5b80d4f8fe0ef3a2959852f0a8ed9cafb5c
Unable to checkout 'dde7f5b80d4f8fe0ef3a2959852f0a8ed9cafb5c' in submodule path 'src/3rdparty/zsync'
```

Should we maybe put zsync in the owncloud umbrella ?

**Comment by ckamm** [comment]
I think that's just the pain of using git submodules like that, it wouldn't go away if it was inside the oc organization. I need to update the pointed submodule ref once the PR there has been merged. (which is done)

**Comment by ckamm** [comment]
Do not merge yet because I need to update the submodule sha1 to the correct one after the zsync PR got merged.

**Comment by ckamm** [comment]
@ogoffart CI fails with
```
src/3rdparty/zsync/c/libzsync/zsync.c:44:23: fatal error: arpa/inet.h: No such file or directory
```
Who do I ask about making this header available?

**Comment by ogoffart** [comment]
> Who do I ask about making this header available?

Modify the  `admin/linux/DockerFile`  and update accordingly the docker image in the `Jenkinsfile`
I gess @dschmidt  might be able to help with that.

**Comment by ckamm** [comment]
@dschmidt I'd add `libc6-dev` to `Dockerfile` for this PR. Would you be able to rebuild the image?

**Comment by ckamm** [comment]
The problem will be resolved by adjusting zsync headers. https://github.com/ahmedammar/zsync/pull/3

**Pull request merged**
