### PR TITLE
remove migrated docs

### PR DESCRIPTION
**Pull request by xoxys**
The documentation was migrated to a dedicated repo https://github.com/owncloud/docs-client-desktop and integrated into the build process https://github.com/owncloud/docs/pull/3647

~Needs backport to 2.7 and 2.8~

### CODE REVIEW

**Review by TheOneRing — APPROVED** [review]

**Review by TheOneRing — CHANGES_REQUESTED** [review]
Just read the backporting part.
2.7 us closed and we usually only merge 2.8 to master and don't backport.

**Comment by xoxys** [comment]
We should IMO definetly bring this back to 2.8 and 2.7 to avoid messup in the docs and to ensure this repo will not push docs anymore.

**Comment by TheOneRing** [comment]
no commit ever is supposed to go to 2.7 :D 
Can you target 2.8?

**Comment by xoxys** [comment]
Ok. Yes I can prepare a PR to 2.8 branch as well

**Comment by xoxys** [comment]
@TheOneRing regardless of the 2.8 backport, can we merge it to master?

**Comment by TheOneRing** [comment]
My idea was to merge this to 2.8 so we can merge 2.8 with master.
If we have two commits I'll get lots of fun with conflicts...

**Pull request merged**
