### PR TITLE
Remove unsupported build instructions

### PR DESCRIPTION
**Pull request by TheOneRing**
The instructions are outdated and likely won't work.
We should not encourage people to waste their time.

### CODE REVIEW

**Comment by TheOneRing** [comment]
And we should add https://github.com/owncloud/ownbuild to the doc

**Comment by michaelstingl** [comment]
> And we should add https://github.com/owncloud/ownbuild to the doc

include in your PR?

**Comment by TheOneRing** [comment]
> 
> 
> > And we should add https://github.com/owncloud/ownbuild to the doc
> 
> include in your PR?

I can do many things... but explaining stuff is not one of them...

**Comment by mmattel** [comment]
> And we should add https://github.com/owncloud/ownbuild to the doc

In case, this should be made in another PR.
You can file a issue (pls mark it as docs) so it will not be forgotten

**Review by mmattel — APPROVED** [review]

**Pull request merged**
