### PR TITLE
For tests we do not need a xserver running.

### PR DESCRIPTION
**Pull request by hefee**
Use for tests QTEST_GUILESS_MAIN and QTEST_APPLESS_MAIN to get rid of a running xserver for tests.

### CODE REVIEW

**Comment by dragotin** [comment]
QTEST_GUILESS_MAIN was introduced with Qt5 it seems, hence this breaks the Qt4 build. Can we do that in a way that this does not happen?

Thanks!!

**Comment by hefee** [comment]
Well to have the same experience on qt4 we need to remove the linkage against QtGui. But I see no way to get rid of GUI, cause they are hardcoded in the QtVersionAbstraction.
But this is still only a "nice addon" to have no xserver running, so I think it is okay to leave qt4 with xserver at the moment.

**Comment by ckamm** [comment]
@hefee :+1: 
@dragotin It does not break the Qt4 build, it only removes the gui dependency for Qt5 builds.

**Comment by dragotin** [comment]
yeah, ok. :+1:

thanks @hefee

**Comment by hefee** [comment]
pushed change to 2.2 branch

**Pull request closed without merging**
