### PR TITLE
Don't abort sync when a token refresh is needed

### PR DESCRIPTION
**Pull request by TheOneRing**
https://github.com/owncloud/ocis/issues/576

### CODE REVIEW

**Review by dschmidt — APPROVED** [review]
Don't know the code, so the actual change is hard to review for me but there's nothing obviously wrong with the PR.

**Comment by guruz** [comment]
It would be nice if " Don't abort sync when a token refresh is needed " could also be a code comment before your code block, just so it's intuitively clear what it is about.
I can't comment on the code itself..

**Comment by TheOneRing** [comment]
I added a comment and added a log message

**Comment by ogoffart** [comment]
I'm not sure chat this fixes.  I thought that we would already refresh the authentication without aborting. Maybe that was not working good?
Would be nice if the commit message could detail the problem and why this fixes it.

**Pull request closed without merging**
