### PR TITLE
Fix initial size of share dialoig

### PR DESCRIPTION
**Pull request by TheOneRing**
@mmattel could you give the build artifact a try to see whether it fixes your issue?

### CODE REVIEW

**Comment by mmattel** [comment]
> give the build artifact a try

can you give me a jump start what this means and how to try it?

**Comment by mmattel** [comment]
If it works, will fix https://github.com/owncloud/client/issues/8366

**Comment by TheOneRing** [comment]
Go to https://github.com/owncloud/client/actions/runs/675876872 download a windows artifact, don't try to run the installer but just extract the contained .7z for example owncloud-client-HEAD-9d921dea8-2.8-windows-msvc2017_64-cl.7z

Make sure owncloud is not running and run the owncloud.exe form that directory, check the about page to ensure your running the right build :)

**Comment by mmattel** [comment]
I tested with the artifact you provided. To get a better impression, I moved the mouse to the taskbar for the screenshot to make the size of the screen more visible. This is how it looks directly after opening the share dialog for the file. I CANNOT reduce the height of the sharing window = smallest size. IMHO there should be a dynamic math behind the screen height with a min value but dependent on the screen height. Just my 2c
image

**Comment by TheOneRing** [comment]
Thx for the screenshot ....
For some reason we set a fixed size for the warning label.
You issue probably also only occurrences when sharing from that share.

**Comment by TheOneRing** [comment]
Hmm no, I can resize it....
image

**Comment by mmattel** [comment]
This is strange. I am using W10x64 latest build an patches but this issue is present for some time now. And all other programs I use do not have this issue.


The interesting thing is, that I can resize the window horizontally, so something must be set to disable it vertically. You see in the image shown the minimum horizontal size I can shrink to:

**Review by dschmidt — APPROVED** [review]

**Review by fmoc — APPROVED** [review]

**Comment by TheOneRing** [comment]
Fixed in 2.9

**Pull request closed without merging**
