### PR TITLE
Sort folder status delegate

### PR DESCRIPTION
**Pull request by TheOneRing**

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/13575/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/13575/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/13575/guiReportUpload/serverlog.log

Screenshots:
- [Adding_account_with_stay_safe_advance_configuration.png](https://cache.owncloud.com/public/owncloud/client/13575/guiReportUpload/screenshots/Adding_account_with_stay_safe_advance_configuration.png)
- [Disable_VFS.png](https://cache.owncloud.com/public/owncloud/client/13575/guiReportUpload/screenshots/Disable_VFS.png)
- [Enable_VFS.png](https://cache.owncloud.com/public/owncloud/client/13575/guiReportUpload/screenshots/Enable_VFS.png)

</details>

**Comment by TheOneRing** [comment]
Ui tests need an update after this change, as the model changed.

**Comment by saw-jan** [comment]
> Ui tests need an update after this change, as the model changed.

I will look at it

**Comment by saw-jan** [comment]
@TheOneRing The GUI tests have been fixed and now are passing: https://drone.owncloud.com/owncloud/client/13609

**Review by fmoc — APPROVED** [review]

**Pull request merged**
