### PR TITLE
Refactor reserved name code

### PR DESCRIPTION
**Pull request by TheOneRing**
~The code also checked whether the strings started with COM8. and returned true in that cas.
While COM8 is reserved COM8.png is ok.~

@michaelstingl maybe only for 2.10?

### CODE REVIEW

**Comment by dschmidt** [comment]
simplify?

**Comment by michaelstingl** [comment]
> @michaelstingl maybe only for 2.10?

yes, sufficient

**Comment by dschmidt** [comment]
Is this covered by tests?
otherwise should be easy enough to test them now while at it

**Comment by TheOneRing** [comment]
So turns out COM8.png is still illegal on Windows 10

**Review by erikjv — APPROVED** [review]

**Pull request merged**
