### PR TITLE
Fix 3490: 403 File Firewall issues

### PR DESCRIPTION
**Pull request by dragotin**
This handles reply of 403 Forbidden in the discovery phase. This is sent if a file firewall is active that prevents the user from uploading to certain directories or certain files.

### CODE REVIEW

**Comment by dragotin** [comment]
@ogoffart please review.
https://github.com/owncloud/client/issues/3490

**Comment by ogoffart** [comment]
Looks good.  Is the code to ignore things not a bit duplicated?

**Comment by ckamm** [comment]
@dragotin This takes care of 403 errors during discovery, can the error also happen for propagation jobs? If someone reconfigures the file firewall to blacklist a folder that's already synced to the client?

The code so far looks ok.

**Comment by dragotin** [comment]
closing to reopen against 2.1

**Pull request closed without merging**
