### PR TITLE
[2.3] Start to migrate to Drone in favor of Jenkins

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by ogoffart** [comment]
The 2.3 branch is dead. (there won't be anymore 2.3 releases)
So I don't believe this is needed.

**Comment by tboerger** [comment]
> The 2.3 branch is dead. (there won't be anymore 2.3 releases)
> So I don't believe this is needed.

Does this mean we can also disable Smashbox nightly tests for this branch?

**Comment by ogoffart** [comment]
> Does this mean we can also disable Smashbox nightly tests for this branch?

Yes.

But that depends what are the smashbox test are testing.
If they are supposed to test the client, yes. It can be stopped.
If they are supposed to test that new server still work with older client, then, they need to be kept.

**Comment by tboerger** [comment]
OK, than let's close this PR.

**Pull request closed without merging**
