### PR TITLE
[Backport][2.4] #6505 Integrate external themes repository 

### PR DESCRIPTION
**Pull request by SamuAlfageme**
- Add the new owncloud/docs-themes repository as a submodule:
	- Remove the outdated submodule reference from the git tree
- Fix broken LTS link to point to Ubuntu's release policy
	- To fix make's client/doc/installing.rst:39: ERROR: Unknown target name: 'lts' on build.
- Also removed references to wizard's last page after https://github.com/owncloud/client/pull/5729
- Set copyright's upper bound dynamically based on the compilation date
	- Ref. https://github.com/owncloud/client/pull/6505\#discussion_r185712624
- Removed CMake-generated files and referenced the right themes path
	- See http://www.sphinx-doc.org/en/master/man/sphinx-build.html

### CODE REVIEW

**Comment by guruz** [comment]
@SamuAlfageme ping. how to proceed?

**Comment by SamuAlfageme** [comment]
@guruz this was due to https://github.com/owncloud/client/pull/6505#issuecomment-386275841 request (IIRC the docs didn't build in 2.4 for some time and there were some updates missing) - CI passing is a good sign. 

However we could take a look at https://github.com/owncloud/client/issues/6572 before merging - whether it's a bug or not since I've always seen the 3 folders (but I'm sure there's a cli switch to build the docs with just one theme - if it's about the manpages, those should not depend on the themes)

**Comment by tboerger** [comment]
2.5 is not really related to this, right?

**Comment by ogoffart** [comment]
@tboerger  right, i just merged it.

**Comment by tboerger** [comment]
Thanks!

**Pull request merged**
