### PR TITLE
Link sharing ui improvements

### PR DESCRIPTION
**Pull request by ckamm**
- Respect fine-grained "password required" capability #7247
- Allow password/expiration to be added to shares that were created
  without these at a time when the server allowed that #7313

### CODE REVIEW

**Comment by guruz** [comment]
Pending discussion in https://github.com/owncloud/client/pull/7564
CC @michaelstingl

**Comment by michaelstingl** [comment]
> Pending discussion in #7564
> CC @michaelstingl

"Hybrid" approach planned mid-term, so I think we'll need this before.

**Comment by ogoffart** [comment]
I fixed the merge conflict based on what i think the code was supposed to do, but this should be reviewed again i guess.

**Comment by TheOneRing** [comment]
I tested the share dilaog and it looks good

could you add a changelog entry?

**Pull request merged**
