### PR TITLE
Sync Folder: Add file manager favorite also in folder wizard #455

### PR DESCRIPTION
**Pull request by guruz**
Not only in the account wizard.

### CODE REVIEW

**Comment by guruz** [comment]
As per the (wrongly worded) comment in https://github.com/owncloud/client/issues/455#issuecomment-291885831

**Comment by jturcotte** [comment]
How does this behave on different platforms if the favorite is already there?

**Comment by guruz** [comment]
@jturcotte This is anyway run only in the add sync folder wizard. I don't know.

**Comment by guruz** [comment]
Just verified, it doesnt duplicate them

**Pull request merged**
