### PR TITLE
make the remaining time string translatable and support plural forms

### PR DESCRIPTION
**Pull request by blizzz**
To fix https://github.com/owncloud/client/issues/2672 just need translations

@danimo is that how to solve it?

(It builds and shows the time string still properly in English)

### CODE REVIEW

**Comment by danimo** [comment]
No, you need to use %n, see http://doc.qt.digia.com/qq/qq19-plurals.html.

**Comment by blizzz** [comment]
Oh, missed this detail :-/ ok, that seems to make it slightly more complicated. Will have a look, ty,

**Comment by blizzz** [comment]
@danimo next attempt. Is this better?

**Comment by ogoffart** [comment]
Unfortunately this won't work.  the string extractors need that the string is directly in the `tr()` call.  This indirection breaks the translation, i'll try to come with a fix

**Comment by blizzz** [comment]
@ogoffart yupp, i forgot to mention it here. I will think of something else.

**Pull request merged**
