### PR TITLE
Change note to warning in documentation

### PR DESCRIPTION
**Pull request by RealRancor**
Follow-up of: https://github.com/owncloud/documentation/issues/1981

Warnings currently looks like seen here: https://doc.owncloud.org/server/9.0/admin_manual/issues/code_signing.html#errors

### CODE REVIEW

**Comment by dragotin** [comment]
@carlaschroder your call, please.

**Comment by guruz** [comment]
@icewind1991 Can you help us with this one?

I wonder if the (original part) is actually true... or shall we mention that the original part is especially valid if ```filesystem_check_changes``` is 0?

**Comment by RealRancor** [comment]
@guruz The original part is there since ages and long before filesystem_check_changes was set to 0 as the default. So a clarification definitely makes sense.

**Comment by guruz** [comment]
Would you like to add the occ scan command or a link to it? Like "if you modified, you need to run..." or so?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: RealRancorSent: Mittwoch, 30. März 2016 11:42To: owncloud/clientReply To: owncloud/clientCc: Markus GoetzSubject: Re: [owncloud/client] Change note to warning in documentation (#4605)@guruz The original part is there since ages and long before filesystem_check_changes was set to 0 as the default. So a clarification definitely makes sense.

—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by RealRancor** [comment]
Thanks for merging. I think this is getting even more important as discussed here: https://github.com/owncloud/core/issues/23783

**Comment by guruz** [comment]
oh well.. :-|

**Pull request merged**
