### PR TITLE
Handle setFileRecord errors #4632

### PR DESCRIPTION
**Pull request by ogoffart**

### CODE REVIEW

**Comment by ogoffart** [comment]
cc @dragotin

**Comment by ogoffart** [comment]
fo issue #4632

**Comment by guruz** [comment]
:-1: Why is there ```Error writing metadata to the database``` and ```Could not write meta data into the local database.```. What's the difference?

**Comment by dragotin** [comment]
Apart from what @guruz said (wording) :+1: from me

**Comment by ogoffart** [comment]
Fixed wording

**Pull request merged**
