### PR TITLE
Add account name to warning message boxes in Folder

### LINKED ISSUE #4545: Missing account name on "Delete all files" confirmation dialog (shows old aliasname instead)
### Steps to reproduce
1. Step up ownCloud and upload files
2. Step up sync client
3. Reset ownCloud (reinstall)

### Expected behaviour
Client shows an confirmation dialog that something strange happens :white_check_mark: 
The error message gives enough information about the issue :x: 

### Actual behaviour
The error message does not give any information which account this is about.
I suspect this is because the error is older then the accounts feature?

bildschirmfoto vom 2016-03-07 12 25 40

### Server configuration
Operating system: Linux Mint

Web server: Apach

Database: MySQL

PHP version: 5.5.32

ownCloud version: 8.2.3-rc1

Storage backend: Local

### Client configuration
Client version: git: 2.1 branch

Operating system: Linux Mint

OS language: German

Installation path of client: ~/ownCloud/Desktop/client-build/

### PR DESCRIPTION
**Pull request by danimo**
Fixes #4545

### CODE REVIEW

**Comment by guruz** [comment]
Why not ```Folder::aliasGui()```?

**Comment by dragotin** [comment]
Please move the accountName() method to the account, not the folder object.

**Comment by danimo** [comment]
@guruz `aliasGui()` does not contain the account name?

**Comment by danimo** [comment]
@dragotin `accountDisplayName()` is mostly an access wrapper as per your please to check 0 ptrs.

**Comment by guruz** [comment]
@danimo Yes but the path :)

And your string "for account" is not correct because one account can have multiple folders..

**Comment by danimo** [comment]
@guruz ok, I'll be more specific then.

**Comment by dragotin** [comment]
@danimo ok, got it. Forget my comment.

**Comment by guruz** [comment]
:-1: ```aliasGui()``` is better.

**Comment by guruz** [comment]
:+1: However the CLA bot fails..
```                           
  [GitHubClientException]  
  Page not defined         
```
https://ci.owncloud.org/job/cla-bot-client/143/console

Who knows stuff here? @karlitschek @DeepDiver1975 ?

**Comment by DeepDiver1975** [comment]
> Who knows stuff here? @karlitschek @DeepDiver1975 ?

already on it ...

**Comment by danimo** [comment]
@guruz bot checks have passed now.

**Pull request merged**
