### PR TITLE
Building doc fixes

### PR DESCRIPTION
**Pull request by suy**
Added some formatting fixes, and updated the installation instructions for OS X. Those need updated Homebrew formulae as well. The matching pull request is: https://github.com/owncloud/homebrew-owncloud/pull/4

More fixes might be needed to have newbie-proof instructions, but I more or less got everything built, so I think is an improvement.

Thank you.

### CODE REVIEW

**Comment by guruz** [comment]
Could you please do https://owncloud.org/contribute/agreement/ ? :-)
Else we're not allowed to merge

FYI @carlaschroder

**Comment by guruz** [comment]
@danimo @jturcotte FYI also regarding our discussions today
```
cmake -D_OPENSSL_LIBDIR=/usr/local/opt/openssl/lib/ -
D_OPENSSL_INCLUDEDIR=/usr/local/opt/openssl/include/  -D_OPENSSL_VERSION=1.0.2a -
DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include/  ../client/
```

@suy Did you not need this magic to get SSL support?

**Comment by suy** [comment]
I've signed the agreement, and sent it to Frank as mentioned in the page.

About OpenSSL, the only magic I needed was -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/, so a bit simpler actually.

**Comment by suy** [comment]
BTW, I didn't knew where I got that from, but is cmake's error message itself:

  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR: Found unsuitable version "0.9.8}", but
  required is at least "1.0.0" (found
  /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib)

**Comment by carlaschroder** [comment]
thanks @suy. I'll have to rely on other reviewers,-- don't be shy other reviewers :) Does this apply only to 2.0?

**Comment by suy** [comment]
The master branch needs some formatting fixes as well. I committed to 2.0 because I thought it would eventually be merged to it. I didn't consider older branches, but building.rst also needs fixes on older branches, at least with respect to formatting.

**Comment by carlaschroder** [comment]
@suy Here is another issue:
https://github.com/owncloud/documentation/issues/1620
"There is outdated info in point 6 at least.

The script of the git client repo is called now create_mac_pkg.sh.cmake"

**Comment by carlaschroder** [comment]
And two more:
https://github.com/owncloud/documentation/issues/1619
https://github.com/owncloud/documentation/issues/1618

@suy @danimo

**Comment by suy** [comment]
Issue https://github.com/owncloud/documentation/issues/1619 is fixed in the formatting fixes of the first commit. I'll review the other two.

**Comment by suy** [comment]
Actually, there are no changes needed after this PR. The export line is gone because brew edit is suggested instead (could require the updates in https://github.com/owncloud/homebrew-owncloud/pull/4). And the build script has the proper name if you look at it at the build directory.

**Comment by suy** [comment]
Due to the changes that were added to 2.0, now the pull request has conflicts because the same formatting changes were done. I'll just abandon it.

**Pull request closed without merging**
