### PR TITLE
Display quota in status delegate

### PR DESCRIPTION
**Pull request by TheOneRing**
image

Clipboard - February 28, 2023 4_24 PM

image

I'd suggest to remove the progress bar we display with oc10

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests-ocis</strong> https://drone.owncloud.com/owncloud/client/14385/7/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/14385/ocis/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/14385/ocis/guiReportUpload/serverlog.log

Screenshots:
- [Adding_account_with_vfs_enabled.png](https://cache.owncloud.com/public/owncloud/client/14385/ocis/guiReportUpload/screenshots/Adding_account_with_vfs_enabled.png)
- [Enable_VFS.png](https://cache.owncloud.com/public/owncloud/client/14385/ocis/guiReportUpload/screenshots/Enable_VFS.png)

</details>

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests-oc10</strong> https://drone.owncloud.com/owncloud/client/14385/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/14385/oc10/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/14385/oc10/guiReportUpload/serverlog.log

Screenshots:
- [Adding_account_with_vfs_enabled.png](https://cache.owncloud.com/public/owncloud/client/14385/oc10/guiReportUpload/screenshots/Adding_account_with_vfs_enabled.png)
- [Enable_VFS.png](https://cache.owncloud.com/public/owncloud/client/14385/oc10/guiReportUpload/screenshots/Enable_VFS.png)
- [Filenames_that_are_rejected_by_the_server_are_reported.png](https://cache.owncloud.com/public/owncloud/client/14385/oc10/guiReportUpload/screenshots/Filenames_that_are_rejected_by_the_server_are_reported.png)
- [collaborators_are_listed_in_chronological_order.png](https://cache.owncloud.com/public/owncloud/client/14385/oc10/guiReportUpload/screenshots/collaborators_are_listed_in_chronological_order.png)
- [unshare_a_shared_file_and_folder.png](https://cache.owncloud.com/public/owncloud/client/14385/oc10/guiReportUpload/screenshots/unshare_a_shared_file_and_folder.png)

</details>

**Comment by TheOneRing** [comment]
@saw-jan the failing tests where image comparisons?

**Review by fmoc — APPROVED** [review]

**Comment by saw-jan** [comment]
> @saw-jan the failing tests where image comparisons?

yeah. Does this PR change anything in the sync folder list view?

**Comment by TheOneRing** [comment]
> > @saw-jan the failing tests where image comparisons?
> 
> yeah. Does this PR change anything in the sync folder list view?

It changes the drawing code and adds the quota line, also fixes to margins etc.

**Comment by saw-jan** [comment]
> It changes the drawing code and adds the quota line, also fixes to margins etc.

Need to update the comparison, We will do it in separate PR but with this merged the CI will not be green

**Pull request merged**
