### PR TITLE
Sharedialog adjustments

### PR DESCRIPTION
**Pull request by ckamm**
Various improvements to looks.

### CODE REVIEW

**Comment by guruz** [comment]
Tested, looks OK to me. Shall we better have this in 2.3?

**Comment by ckamm** [comment]
@guruz I think it's sufficiently safe for 2.3, do you want to retarget?

**Comment by guruz** [comment]
>  continuous-integration/jenkins/pr-merge — This commit cannot be built

Feel free to manually merge in 2.3 or master

**Comment by ckamm** [comment]
Was merged into 2.3. The test failure on CI was unrelated, this literally only adjusts UI.

**Pull request closed without merging**
