### PR TITLE
Update offline icon

### PR DESCRIPTION
**Pull request by TheOneRing**
Fixes: #11905

Old:
image
New:
image

### CODE REVIEW

**Comment by TheOneRing** [comment]
@tbsbdr the icon appears to be "576x512".... which might cause issues....

**Comment by tbsbdr** [comment]
what should it be? 1:1?

**Comment by TheOneRing** [comment]
> what should it be? 1:1?

Yes. 512x512

**Comment by tbsbdr** [comment]
so do we always need to customize icons taken from font awesome? they all seem to vary their aspect ratio :(
how did we deal eg. with the plug icon in the past? - same problem here
screenshot_003178

**Comment by TheOneRing** [comment]
hmm, I think this might no longer be an issue and had been a legacy condition from the time we used different sized pngs....

**Comment by erikjv** [comment]
I checked (on macOS) and the icon is proportionally scaled (meaning: it doesn't look squashed/stretched in one direction)

**Pull request merged**
