### PR TITLE
Settings: Add update channel combobox

### PR DESCRIPTION
**Pull request by ckamm**
Open questions / things this doesn't do:
- Should it ever be hidden when the "Updater" group is shown?
- As a user I'd expect that when I switch the release channel I'll be offered to download the newest version from that channel. I think this important and I'll look at it.

Intended for picking into 2.4 once merged.

For  #6259

### CODE REVIEW

**Comment by ogoffart** [comment]
One problem is that the users are already compleining that the settings dialog is too tall. And I have not seen the result, but I suspect only makes the settings dialog taller.

**Comment by ckamm** [comment]
@ogoffart Indeed a problem. I ended up not adding another row to the "Updates" groupbox so the effect should be minor. We do definitely need to rework the settings ui to not make this a problem.

**Comment by guruz** [comment]
This is how would look (if SparkleUpdater was an OCUpdater):
screen shot 2018-04-26 at 14 50 41

**Comment by guruz** [comment]
> One problem is that the users are already compleining that the settings dialog is too tall.

@ogoffart The idea was to move the complete About-section into a new window that is accessible as "About" item from tray menu. Do you want to do this? (independant of the fact that @ckamm didnt increase the size)

**Comment by guruz** [comment]
@ckamm Pushed showing the UI on macOS.
The state won't be shown, we can improve this at another commit (not for 2.4.2)

screen shot 2018-04-27 at 09 32 25

**Comment by guruz** [comment]
^^ FYI @michaelstingl @SamuAlfageme

**Comment by michaelstingl** [comment]
Where is this located?

@SamuAlfageme put in your planned "advanced" section?

**Comment by SamuAlfageme** [comment]
@michaelstingl it's in the "About" section - last HBox in there is shown for the clients with the updater enabled when it has meaning (notify about updates - e.g. not with Sparkle).

And yes, it's one of those ideas to include on a future, leaner "Settings" redesign.

**Comment by ckamm** [comment]
There was a bunch of discussion and obstacles around the question of what going from `beta` to `stable` would do.
- On OSX downgrading isn't possible
- Downgrading is potentially unsafe everywhere

A discussed behavior would be:
- Move from `stable` to `beta`: Show an extra message explaining the details, including not being able to return to stable immediately (as a link to documentation)
- When going from `beta` to `stable`: Explain that the change won't take effect immediately, but only when a newer `stable` version comes out that comes after the currently installed version.

Given these constraints, it doesn't seem to me like this is something regular users would want to do since there's a chance they'll be on a broken `beta` version without the ability to go back. @SamuAlfageme Could you explain the usecase to me again?

**Comment by guruz** [comment]
@ckamm I think you are overthinking this. I think it's fine how it works now. Users will understand that they need to download a stable version manually if they want to go back.

**Pull request merged**
