### PR TITLE
Wizard: Increase vertical size to fit error text

### PR DESCRIPTION
**Pull request by ckamm**
After some complex attempts of adding vertical scroll bars if the size got out of hand, I opted to just increase the window size if necessary.

For  #6546

### CODE REVIEW

**Comment by SamuAlfageme** [comment]
@ckamm everything looks right code-wise but can't see the patch working on windows - still reproducing with the steps on https://github.com/owncloud/client/issues/6546#issuecomment-394312492 and with the spinner standalone 😕

**Comment by ckamm** [comment]
@SamuAlfageme That's frustrating, it works for me on linux now. Does the wizard window increase in size at all when the error label becomes visible?

**Comment by ogoffart** [comment]
I tried the patch on linux (Kwin),  and the patch does not seem to have any effect.
The window is not resized.

Also i'm wondering if we should not prevent the window to make the size smaller, or change the horizontal size.

(Note: for your testing, are you using branding? because branded client size the wizard differently as there is no pixmap.  (I was not using branding) )

**Comment by SamuAlfageme** [comment]
@ogoffart nope, no branding involved:

wizard_resize_issues

**Comment by ckamm** [comment]
My test setup used a different code path to setting errors - indeed nothing is done for network errors, my oversight. But even if I make the resize happen, the checkboxes are still squished together in my windows tests. I think this does need something that scrolls.

**Comment by guruz** [comment]
Superseded by https://github.com/owncloud/client/pull/6589 ?

**Comment by ckamm** [comment]
Indeed.

**Pull request closed without merging**
