### PR TITLE
Update Overlay Icon naming for Windows

### PR DESCRIPTION
**Pull request by mmattel**
Refernces: https://github.com/owncloud/client/issues/6204 (Better naming of description and extension name in OCOverlays_x64.dll)

The naming is now updated according the suggestion in the referenced issue.
Please note that we have anyways in the field "Compmany" and "LegalCopyright" and the naming ``ownCloud``. Therefore this is not an issue.

**See current text in OCOverlay.rc:**
```
BEGIN
            VALUE "CompanyName", "ownCloud Inc."
            VALUE "FileDescription", "Windows Shell Overlay Icon Handler"
            VALUE "FileVersion", OCEXT_VERSION_STRING
            VALUE "InternalName", "OCOverlays"
            VALUE "LegalCopyright", "Copyright (C) 2014-2015 ownCloud Inc."
            VALUE "ProductName", "Windows Shell Overlay Icon Handler"
            VALUE "ProductVersion", OCEXT_VERSION_STRING
END
```

**See new text in OCOverlay.rc:**
```
BEGIN
            VALUE "CompanyName", "ownCloud Inc."
            VALUE "FileDescription", "ownCloud shell extension"
            VALUE "FileVersion", OCEXT_VERSION_STRING
            VALUE "InternalName", "OCOverlays"
            VALUE "LegalCopyright", "Copyright (C) 2014-2015 ownCloud Inc."
            VALUE "ProductName", "ownCloud shell extension"
            VALUE "ProductVersion", OCEXT_VERSION_STRING
END
```

@SamuAlfageme

### CODE REVIEW

**Comment by ogoffart** [comment]
Looks good, but note that this is not branded.  Is that a problem @michaelstingl ?  Is it better to see "OC" than "ownCloud" on the branded client?

**Comment by michaelstingl** [comment]
Where is this shown for the end user? Screenshot?

**Comment by mmattel** [comment]
The ordinary end user usually never sees that as he will not do debugging/tests.
You only see this when you go into the registry or use ``ShExtView`` (as described in the Wiki).
The secreensot is in the refernced issue, I did not copied it again.
When you run into a problem with OverlayIcons and look/search for it, this PR helps finding/identifying stuff MUCH easier.

**Comment by michaelstingl** [comment]
Okay, works for me! 👍

**Pull request merged**
