### PR TITLE
Retry update after 10 minutes

### LINKED ISSUE #9522: Retry auto-update after network failure
tbd

### PR DESCRIPTION
**Pull request by fmoc**
Fixes #9522.

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11097/5/1
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11097/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/11097/guiReportUpload/serverlog.log)

**Comment by TheOneRing** [comment]
@Talank why are the squis logs green but the gui test step red?

**Review by TheOneRing — APPROVED** [review]

**Review by TheOneRing — CHANGES_REQUESTED** [review]
Changelog

**Review by TheOneRing — APPROVED** [review]

**Comment by Talank** [comment]
I am not sure why the GUI test result did not find the failed test. I think there is a crash `LookupError: Lost connection to AUT` Same as in https://github.com/owncloud/client/issues/9367.
For details, please refer to the test result data (generated in JS format) https://cache.owncloud.com/public/owncloud/client/11097/guiReportUpload/data/results-v1.js

**Comment by TheOneRing** [comment]
thx

**Pull request merged**
