### PR TITLE
OS X: Allow ampersand in APPLICATION_NAME #4657

### PR DESCRIPTION
**Pull request by guruz**

### CODE REVIEW

**Comment by ogoffart** [comment]
While you are at it, i think you should also replace '<' and '>'
Is there other fields that would need to be escaped?

**Comment by guruz** [comment]
@ogoffart I grepped for ```APPLICATION_NAME``` but did not find anything more..
I also tested via the build server and the OS X builds worked..

I will add the gt/lt

**Comment by guruz** [comment]
Updated commit

**Comment by dragotin** [comment]
For XML you need to escape 
```
"   &quot;
'   &apos;
<   &lt;
>   &gt;
&   &amp;
```
And once we build a client for *"Claude's Client Cloud"* we will need the quotes excaped.

**Comment by ogoffart** [comment]
:+1:   

Quotes need not to be escaped in this case since APPLICATION_NAME is inside an element and not in an atribute

**Comment by dragotin** [comment]
but would it hurt?

**Comment by guruz** [comment]
@dragotin I'll merge it for now then, we indeed don't use it inside attributes.
If I add the support for quotes, I'll need to escape the quotes _inside cmake_ :-) I'm worried to fall into an inception trap.

**Comment by dragotin** [comment]
ok, I see. Thanks.

**Pull request merged**
