### PR TITLE
Fix vfs wizard issues

### PR DESCRIPTION
**Pull request by TheOneRing**
@HanaGemela did I fix the correct issue with the fix for #7710

### CODE REVIEW

**Comment by ogoffart** [comment]
Why was it crashing?

I'm not a fan of using exec() as it makes the callstack deeper and sometimes can have even worse problems.

If some pointer get dangling, maybe they need to be wrapped in a QPointer and tested.

**Comment by TheOneRing** [comment]
I use exec() as it should be a modal dialog.
Users should be forced to accept or decline before they can do anything else.
If we didn't do soemthing evil I wouldn't expect issues by calling exec().

The crash was caused by by the caller being deleted before the signal was emitted.
So the receiver didn't exist anymore, in a connect the receiver should always be specified to determine the live time of the lambda.

Making the dialog blocking fixes the issue with multiple dialogs as the user can't click on the radio button while the dialog is displayed.

**Comment by ogoffart** [comment]
`QDialog::open` should also be model. It is documented as such.  Maybe the problem is that the parent is not properly set?

And indeed, it may be worth to specify a better receiver.  

But what exactly is deleted too early in this case?

**Comment by TheOneRing** [comment]
> `QDialog::open` should also be model. It is documented as such. Maybe the problem is that the parent is not properly set?
> 
> And indeed, it may be worth to specify a better receiver.
> 
> But what exactly is deleted too early in this case?

The non modal dialog is displayed, the user ignores it, and closes the wizard, or ownCloud.
During destruction of the dialog the the finished signal is emitted, the callback is executed but the variables referenced in the lambda do no longer exist.

**Comment by TheOneRing** [comment]
@ogoffart should be ready now

**Pull request merged**
