### PR TITLE
Nautilus shell integration: Port to Python 3

### PR DESCRIPTION
**Pull request by ogoffart**
This is still WiP, as I don't know if it will work with python 2.7

Any suggestion on how to make it compatible with both?

### CODE REVIEW

**Comment by ckamm** [comment]
Huh, can we tell which python version nautilus is using to process the shell integrations? (I was also wondering whether I can use `time.monotonic()` which is in >=3.3 only)

**Comment by ckamm** [comment]
FWIW my nautilus on Ubuntu 17.10 uses Python 2.7.14 (sys.version).

**Comment by ogoffart** [comment]
On my archlinux it is using python 3

I think this is because i don't have python2-nautilus installed, and maybe installing it would have fixed my problem without porting to python3

Possibly, we can force python 3 by adding `#!/usr/bin/env python3`   as the first line

**Comment by ckamm** [comment]
@ogoffart No, the file is not being `exec()`ed but loaded into some custom python context that probably comes with a specific version. (I tried)

**Comment by ckamm** [comment]
And these changes don't work with the 2.7 version. It seems we'll have to do version detection in the scipt.

**Comment by ckamm** [comment]
The updated version works with my python2 based nautilus. Please double check against python3.

**Comment by ogoffart** [comment]
Merged manually. 
(There was still a few encode missing in code path that i had not ran before)

**Pull request closed without merging**
