### PR TITLE
Consistently use folder icon

### PR DESCRIPTION
**Pull request by TheOneRing**
# Old
thumb-Clipboard - September 7, 2023 11 38
#New
thumb-Clipboard - September 7, 2023 11 52

### CODE REVIEW

**Review by erikjv — APPROVED** [review]

**Comment by HanaGemela** [comment]
@TheOneRing what are the steps to test?

**Comment by TheOneRing** [comment]
As you can see you won't see the system icons for folders anymore

**Comment by TheOneRing** [comment]
Grr I copied the images from rocket chat and it only took the thumbnail instead of the actual full size image..

**Comment by HanaGemela** [comment]
Test just one platform

**Comment by HanaGemela** [comment]
Passed in ownCloud 5.0.0.12077-daily20230908, mac

**Pull request merged**
