### PR TITLE
Disable autostartCheckbox if autostart is configured system wide

### PR DESCRIPTION
**Pull request by dschmidt**

### CODE REVIEW

**Comment by dschmidt** [comment]
Hehe, the monoIconsCheckbox apparently was already at the bottom because it can be hidden by the theme ... suggestions how to handle this without overcomplicating the code?

**Comment by dschmidt** [comment]
I like that! Will do!

**Comment by dschmidt** [comment]
Tested on Win7 and Win10.

**Comment by guruz** [comment]
(Forgot to mention issue ID in commit..i think with enterprise issues we often forget that)

**Pull request merged**
