### PR TITLE
Remove need for UPDATE_VIEW to refetch the status #2340

### PR DESCRIPTION
**Pull request by jturcotte**

### CODE REVIEW

**Comment by danimo** [comment]
@ogoffart please comment on the items

**Comment by guruz** [comment]
@ogoffart Probably best to move into the beta to get most testing?

@jturcotte It would be good to mention the improved/fixed issue numbers in the commits (if there is issues..)

This would help the Eagle-issue?

**Comment by jturcotte** [comment]
@guruz This is currently only the case for OS X 10.10, others are still doing the refetching but possibly unnecessarily. We can change that for 2.1, but the eagle-issue should already be fixed with the status cache cleaning patch that went into 1.8.x

**Comment by jturcotte** [comment]
Anybody interested in touching that soft "Merge pull request" button?

**Pull request merged**
