### PR TITLE
Enable appveyor builds

### PR DESCRIPTION
**Pull request by dschmidt**

### CODE REVIEW

**Comment by ogoffart** [comment]
looks good, the build is passing :-)

**Comment by dschmidt** [comment]
I can probably add a status image to the readme :)

**Comment by ogoffart** [comment]
I'm currious... how does this work?  I don't see the call to cmake. Is craft doing that? how does it know how to run cmake?

**Comment by dschmidt** [comment]
@ogoffart https://github.com/owncloud/craft-blueprints-owncloud/blob/master/owncloud/owncloud-client/owncloud-client.py#L25

**Comment by dschmidt** [comment]
We talked about it. Yes, that's indeed a (minor) problem because UNIT_TESTING enables additional codepaths that are undesirable in release builds. @ogoffart will take care of getting rid of it.

**Pull request merged**
