### PR TITLE
Fix ownCloud icon in unbranded installer

### PR DESCRIPTION
**Pull request by ChrisEdS**
Fix ownCloud icon in unbranded installer

### CODE REVIEW

**Comment by michaelstingl** [comment]
@dschmidt Could you check why the AppVeyor complains?

**Comment by dschmidt** [comment]
@michaelstingl yup, unrelated - will look into it this week.

**Comment by ogoffart** [comment]
This should be rebased in 2.4 I guess

**Comment by michaelstingl** [comment]
@ogoffart @dschmidt What's needed to merge this? Is this used in the MSI too?

2.4.1 would be nice, but 2.5.0 would be enough.

**Comment by ogoffart** [comment]
manually merged in 2.4

**Pull request closed without merging**
