### PR TITLE
[ci] Refine drone.star config

### PR DESCRIPTION
**Pull request by saw-jan**
Noticeable changes:
- building desktop-client in one pipeline step (gitsubmodule + generate + ninja)
- build GUI test pipelines based on config provided
- keep only one ctest pipeline in nightly
- remove `-j4` while building client
- enable gui test against oc10 on PRs using `full-ci`

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests-ocis</strong> https://drone.owncloud.com/owncloud/client/15016/7/1

<details>


</details>

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests-ocis</strong> https://drone.owncloud.com/owncloud/client/15019/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/15019/ocis/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/15019/ocis/guiReportUpload/serverlog.log

Screenshots:
- [Add_space_manually_from_sync_connection_window.png](https://cache.owncloud.com/public/owncloud/client/15019/ocis/guiReportUpload/screenshots/Add_space_manually_from_sync_connection_window.png)

</details>

**Comment by TheOneRing** [comment]
ninja without an argument should use the number of cores available by default.
ctests only runs one test at a time unless -j is used.

**Comment by saw-jan** [comment]
> Any reason to still use make?

There are two different build pipelines during nightly: one with `ninja` and one with `make`.
here: https://github.com/owncloud/client/blob/384fbe693b99184f0aea6c67badccd3dbd8c5f3e/.drone.star#L88-L102
using ninja is enough?

**Review by individual-it — APPROVED** [review]

**Pull request merged**
