### PR TITLE
Replace ocsjob with JsonApiJob

### PR DESCRIPTION
**Pull request by TheOneRing**

### CODE REVIEW

**Review by fmoc — APPROVED** [review]
Looks significantly better than the previous setup. Good job!

**Comment by TheOneRing** [comment]
@Talank could you elaborate what the failing test does maybe I can run the scenario manually

**Comment by Talank** [comment]
> @Talank could you elaborate what the failing test does maybe I can run the scenario manually

This is the scenario that fails https://github.com/owncloud/client/blob/ea7cb16ba02b49df94d2d436da1cc76bac594a89/test/gui/tst_sharing/test.feature#L240

Steps to test manually:
- create 4 users "Alice", "Brian", "Carol", and "David"
- as user Alice, upload a file with some content. Use web/api to upload the file
- In client, set up user Alice
- As user Alice, share the uploaded file with different users (share using client-UI)
```
            | user         | permissions |
            | Brian Murphy | edit,share  |
            | Carol King   | edit,share  |
            | David Lopez  | edit,share  |
```
- Then the users should be listed as collaborators with appropriate permissions (in client-UI)

**Review by erikjv — APPROVED** [review]

**Comment by TheOneRing** [comment]
I will fix the unit tests once we have log files....

**Pull request merged**
