### PR TITLE
improved linux build instructions.

### PR DESCRIPTION
**Pull request by jnweiger**
I am using :: lists, as the ``  versions mangle multi-line commands all in one long line.
The cmake command should just end in .., not in ../client

@Kawohl this should also work in your Dockerfile.

### CODE REVIEW

**Comment by dragotin** [comment]
:+1: thanks!

**Comment by dragotin** [comment]
@carlaschroder ok to merge?

**Comment by carlaschroder** [comment]
Lines 212 and 215 have formatting errors, there needs to be a space separating the leading two dots and note, like this: .. note::

**Comment by carlaschroder** [comment]
I have not had time yet to test the steps :( I need to learn how to build the client.

**Comment by carlaschroder** [comment]
You can merge this when the markup errors are fixed.

**Comment by jnweiger** [comment]
merged after fixing the formatting. Thanks!

**Pull request merged**
