### PR TITLE
LogWindow: Remove output, add "go to log folder" button

### PR DESCRIPTION
**Pull request by ckamm**
For  #6475

image

### CODE REVIEW

**Comment by guruz** [comment]
How is the ```--logdebug```flag handled now?

**Comment by michaelstingl** [comment]
😍 /cc @ChrisEdS FYI

**Comment by ckamm** [comment]
@guruz The persistent logging is always with `--logdebug`.

**Comment by ckamm** [comment]
Further updated with doc changes and a new screenshot of the log output window.

**Comment by guruz** [comment]
Hmmm I don't really think it's necessary to `tr()` in this window but i don't have a strong opinion on this

**Comment by guruz** [comment]
Ugly on windows directly after pressing the Fx key:
Screen Shot 2019-04-10 at 11 48 25

**Comment by ckamm** [comment]
@guruz I've adjusted the layout to look a bit better. There's still some unnecessary whilespace but it's in a better location now. And it's just the debug log window.

**Pull request merged**
