### PR TITLE
Utf8 fix

### PR DESCRIPTION
**Pull request by individual-it**
fixes the unicode issue #3753
I don't know much CPP and Qt but after some google research I found this http://wiki.qt.io/Strings_and_encodings_in_Qt
it does mention ````trUtf8()```` that has done the trick for me on Linux with Gnome 3.16.
Haven't tested it on other systems

P.S. sorry for the messy commits. I had my other PR in my master branch and tried to make this PR only having the one fix in it.

### CODE REVIEW

**Comment by dragotin** [comment]
Nice, makes sense. But why does this PR have so many commits? Please re-submit with only one commit fixing the tr issue. Thanks.

**Comment by individual-it** [comment]
That's because of my other outstanding PRs #3663 & #3691 
I accidentally got that changes into my forked master branch. So I had to do the utf8-fix branch on that basis again and to revert that PRs from my master.
So from what I understand of git & github I could wait till PRs #3663 & #3691 are merged and then delete my complete fork and refork, apply the UTF8 fix again and submit a new PR or I could create a branch in owncloud/client itself, what I didn't dare to do so far.
Or is there an other way to solve that?

**Comment by phil-davis** [comment]
You can just go to the master in the real ownCloud client GitHub and edit the file online. It will create a branch automagically when you save the edit. Then it will suggest a pull request...
I never branch anything of the master of my forked copy of the repo.

**Comment by phil-davis** [comment]
The new PR https://github.com/owncloud/client/pull/3777 looks much cleaner, so closing this one.

**Comment by individual-it** [comment]
@phil-davis yes that creates a new branch in owncloud/client itself
have done that now. So closing this PR in favour of #3777

**Pull request closed without merging**
